### ISSUE TITLE
Reference File organization

### ISSUE THREAD

**Issue by apeltzer** [nf-core/eager#1]
- [ ] Human Reference Genomes (GRCH37, HG19, rCRS, RSRS, GRCH38)

If the schmutzi opt files are not specified on command line, one could also offer to download these specifically in a single step...

**Comment by apeltzer** [comment]
The schmutzi bioconda recipe will hopefully contain all required reference files for schmutzi - we could simply link that URL (inside the container) then by default. 

For other reference genomes - one could define a general path to e.g. standard genomes and make that generic, so that users can have a directory with reference genomes that is then commonly used for their analysis (e.g. set to read only).

```bash
nextflow run nf-core/eager --genome "GRCH37" --genomepath /path/to/your/references 
``` 
This would then pick up all kinds of indices for various use-cases and the users can then rely on these being correct.

**Comment by ewels** [comment]
This is basically what we already do in the other pipelines with the igenomes config, right? Could also add whatever you’re missing to igenomes..

**Comment by apeltzer** [comment]
Also related to https://github.com/nf-core/eager/issues/56

**Comment by apeltzer** [comment]
I guess we'll be fine with lots of the stuff in iGenomes and potentially add some of the missing ones to iGenomes then. As long as people can still use custom stuff (which is and will be possible, there won't be much to do here...)
