### ISSUE TITLE
Add GenConS as alternative to VCF2Genome

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#10]
To continue with aDNA specific tools, we could consider adding 'GenConS', which is a part of of the TOPAS package - https://github.com/subwaystation/TOPAS

This allows you to generate a consensus sequence but with a punishment score on possible C to T deamination lesions.

**Comment by jfy133** [comment]
Maybe PMD tools too? Although not sure how/where that would exactly fit in. But running downstream on damage only reads is something people working on older samples do sometimes.

**Comment by apeltzer** [comment]
PMDtools was on the list already yes :-)

**Comment by jfy133** [comment]
This unfortunately isn't being developed any more, and I'm getting reports that bugs are popping up every now and then. I think it's safer (but sad) to not include this.
