### ISSUE TITLE
DSL2: Add bedtools coverage

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#1002]
for 1 to 1 parity with eager2

**Comment by shyama-mama** [comment]
@jfy133 I've added the bedtools coverage step from eager 2. I came up with a very ugly solution to get 
`samtools view -H ${bam} | grep '@SQ' | sed 's#@SQ\tSN:\\|LN:##g' > genome.txt` working using the existing samtools view module. 
But it seems to work. Let me know if there is a more graceful way to do this.

**Comment by jfy133** [comment]
Do you have a PR/branch I can look at the code at? If it's too hacky we can always make a local module :)

**Comment by jfy133** [comment]
*A local module meaning an unofficial module used only for this pipeline

**Comment by shyama-mama** [comment]
Pull request created here
https://github.com/nf-core/eager/pull/1005
