### ISSUE TITLE
DSL1: Input file name collision when merging two already merged BAMs in `additional_library_merge` step.

### ISSUE THREAD

**Issue by TCLamnidis** [nf-core/eager#1017]
## Check Documentation

I have checked the following places for your error:

- [x] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [x] [nf-core/eager pipeline documentation](https://nf-co.re/nf-core/eager/usage)
      - nf-core/eager FAQ/troubleshooting can be found [here](https://nf-co.re/eager/usage#troubleshooting-and-faqs)

## Description of the bug
In niche cases where multiple UDG treatments exist for a sample, and multiple libraries have each of these treatments, a file name collision kills the pipeline at the `additional_library_merge` step.

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: `nextflow run ...` (any input that requires merging of two already merged library-level BAMs during `additional_library_merge` step.
2. See error: 

```
Caused by:
  Process `additional_library_merge` input file name collision -- There are multiple input files for each of the following file names: MIS010_ss_libmerged.trimmed.bam, MIS010_ss_libmerged.trimmed.bam.bai
```

## Expected behaviour

The BAMs initial libmerged should have unique names, to avoid such errors.

## Log files

Have you provided the following extra information/files:

- [ ] The command used to run the pipeline
- [ ] The `.nextflow.log` file 
- [x] The exact error: 

## System

- Hardware: HPC
- Executor: sge 
- OS: Ubuntu
- Version 20.04.6 LTS 

## Nextflow Installation

- Version:  21.10.6 build 5660

## Container engine

- Engine: Singularity
- version: singularity version 3.7.1
- Image tag: 2.4.5

**Comment by jfy133** [comment]
> In niche cases where multiple UDG treatments exist for a sample, and **multiple libraries have each of these treatments**, a file name collision kills the pipeline at the additional_library_merge step.

That's what confuses me... shouldn't they have been merged at the first post-dedup merging step? :thinking:
