### ISSUE TITLE
DSL2: add circularmapper module

### ISSUE THREAD

**Issue by shyama-mama** [nf-core/eager#1033]
for parity with eager2

**Comment by shyama-mama** [comment]
Looks like CircularMapper does not already have a nf-core module. Will need to make one following the tutorial here. 
https://nf-co.re/docs/contributing/tutorials/dsl2_modules_tutorial

**Comment by shyama-mama** [comment]
I've made a pull request on nf-core modules here for circular mapper:
https://github.com/nf-core/modules/pull/4320

There are some strange errors with pytests even though they work fine locally. Awaiting help from nf-core devs.

**Comment by TCLamnidis** [comment]
ok. They are currently migrating to nf-tests, so you could try to set up those instead of using pytest potentially.
