### ISSUE TITLE
MultiQC Config doesn't separate the two FASTQC runs

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#107]
**Describe the bug**
Only a single FastQC module is present in the MultiQC output - where the pipeline runs the tool twice (before and after adapter clipping). 

There should be one for each.

**To Reproduce**
```
nextflow run nf-core/eager \
-profile standard,conda \
--reads '/projects1/users/fellows/nextflow/eager2/dev_testing/data/ABM006.A0101/*_R{1,2}*fastq.gz' \
--pairedEnd \
--fasta '/projects1/users/fellows/nextflow/eager2/dev_testing/references/tannerella_forsythia_actual/Tannerella_forsythia_9212.fa' \
--outdir '/projects1/users/fellows/nextflow/eager2/dev_testing/eager2/01-actual_reference/tannerella_forsythia/ABM006.A0101' \
--name 'eager_nextflow_dev' \
--email fellows@shh.mpg.de \
--max_cpus 4 \
--max_mem 32G \
--skip_preseq \
--min_adap_overlap 1 \
--clip_readlength 30 \
--clip_min_read_quality 20 \
--bwaalnn 0.01 \
--bwalnl 32 \
--bam_discard_unmapped \
--bam_unmapped_type discard \
--dedupper dedup 
--dedup_all_merged \
-r dev

```

**Expected behavior**
Need to modify multiQC  config to pick up the FASTQC files separately.

**Comment by jfy133** [comment]
See: https://multiqc.info/docs/#order-of-modules

**Comment by jfy133** [comment]
Potential fix in PR #109

**Comment by apeltzer** [comment]
Can we add the previous modules back in there as well to keep the order of the modules in the mUltiqc report identical everytime?

**Comment by apeltzer** [comment]
https://github.com/nf-core/eager/pull/110 fixes the issue :-)
