### ISSUE TITLE
vcf2genome error

### ISSUE THREAD

**Issue by dbajpp0** [nf-core/eager#1086]
Dear Eager developer,
I found an error on converting vcf file from GATK ug with vcf2geome.
  Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3280
  	at VCF2Genome.runUGAnalysis(VCF2Genome.java:284)
  	at VCF2Genome.<init>(VCF2Genome.java:148)
  	at VCF2Genome.main(VCF2Genome.java:129)
I send full error and nextflow log below. I also added info about OS, eager and nextflow as well as full command line input
Could you pleae help me to sort it out?
Thanks in advance,
Joan

## Check Documentation

I have checked the following places for your error:

- [ x] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [x ] [nf-core/eager pipeline documentation](https://nf-co.re/nf-core/eager/usage)
      - nf-core/eager FAQ/troubleshooting can be found [here](https://nf-co.re/eager/usage#troubleshooting-and-faqs)

## Description of the bug

Pipeline completed with errors-
Error executing process > 'vcf2genome (50lib_myotragus_reads_clean_mapped)'

Caused by:
  Process `vcf2genome (50lib_myotragus_reads_clean_mapped)` terminated with an error exit status (1)

Command executed:

  pigz -d -f -p 1 50lib_myotragus_reads_clean_mapped.unifiedgenotyper.vcf.gz
  vcf2genome -Xmx100g -draft 50lib_myotragus_reads_clean_mapped_UGVCFcsus.fasta -draftname "csusUG" -in 50lib_myotragus_reads_clean_mapped.unifiedgenotyper.vcf -minc 5 -minfreq 0.8 -minq 20 -ref Ovis_RNA_centroids95_part1.fa -refMod 50lib_myotragus_reads_clean_mapped_UGVCFcsus.fasta_refmod.fasta -uncertain 50lib_myotragus_reads_clean_mapped_UGVCFcsus.fasta_uncertainty.fasta
  pigz -f -p 1 50lib_myotragus_reads_clean_mapped_UGVCFcsus.fasta*
  bgzip -@ 1 *.vcf

Command exit status:
  1

Command output:
  VCF2Genome (v. 0.91 2017-01-13)
  by Alexander Herbig (<= v0.84) and Alexander Peltzer (>v0.84)
  herbig@shh.mpg.de, peltzer@shh.mpg.de
  
  SNP statistics
  Quality Threshold: 20.0
  Coverage Threshold: 5
  Minimum SNP allele frequency: 0.8
  sample	SNP Calls	coverage(fold)	coverage(percent)	refCall	allPos	noCall	discardedRefCall	discardedVarCall	filteredVarCall	unhandledGenotype

Command error:
  VCF2Genome (v. 0.91 2017-01-13)
  by Alexander Herbig (<= v0.84) and Alexander Peltzer (>v0.84)
  herbig@shh.mpg.de, peltzer@shh.mpg.de
  
  SNP statistics
  Quality Threshold: 20.0
  Coverage Threshold: 5
  Minimum SNP allele frequency: 0.8
  sample	SNP Calls	coverage(fold)	coverage(percent)	refCall	allPos	noCall	discardedRefCall	discardedVarCall	filteredVarCall	unhandledGenotype
  Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3280
  	at VCF2Genome.runUGAnalysis(VCF2Genome.java:284)
  	at VCF2Genome.<init>(VCF2Genome.java:148)
  	at VCF2Genome.main(VCF2Genome.java:129)

Work dir:
  /dades/jpp/data_WG_myotragus/eager/part1/work/5c/ab0ab35e55577260d159fd471ea82f

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: `nextflow run ...`
2. See error: _Please provide your error message_

## Log files

Have you provided the following extra information/files:

- [ ] The command used to run the pipeline
-  nextflow run nf-core/eager -profile docker -resume --fasta /dades/jpp/references/Ovis_RNA_centroids95_part1.fa --mapper bwamem --skip_fastqc --skip_adapterremoval --outdir /dades/jpp/data_WG_myotragus/eager/part1 --single_end --input /dades/jpp/data_WG_myotragus/clean_joan/mapped_reads/50lib_myotragus_reads_clean_mapped.fastq.gz --max_cpus 7 --max_memory 100.GB --max_time 500.h --run_vcf2genome true --vcf2genome_minc 5 --vcf2genome_minq 20 --vcf2genome_minfreq 0.8 --vcf2genome_header csusUG --vcf2genome_outfile UGVCFcsus --run_genotyping true --genotyping_tool ug --genotyping_source raw --gatk_call_conf 20 --gatk_ploidy 2 --gatk_ug_genotype_model SNP --gatk_ug_keep_realign_bam true --dedupper markduplicates --run_bam_filtering true --bam_unmapped_type discard --bam_mapping_quality_threshold 20 --gatk_ug_out_mode EMIT_ALL_SITES

- [ ] The `.nextflow.log` file 
[nextflow.log](https://github.com/user-attachments/files/16927944/nextflow.log)

- [ ] The exact error: 

## System

- Hardware: 
- Executor: 
- OS: 
- Version 

## Nextflow Installation

- Version: 

## Container engine

- Engine: 
- version: 
- Image tag:

**Comment by jfy133** [comment]
I'm very very sorry @dbajpp0 this completely slipped out of my TODO list

Unfortunately this appears to be an error with VCF2Genome.

I would suggest going into the working directory (if you still have the run ` /dades/jpp/data_WG_myotragus/eager/part1/work/5c/ab0ab35e55577260d159fd471ea82f`) and send all the files there and the command eager is trying to execute (` vcf2genome -Xmx100g -draft 50lib_myotragus_reads_clean_mapped_UGVCFcsus.fasta -draftname "csusUG" -in 50lib_myotragus_reads_clean_mapped.unifiedgenotyper.vcf -minc 5 -minfreq 0.8 -minq 20 -ref Ovis_RNA_centroids95_part1.fa -refMod 50lib_myotragus_reads_clean_mapped_UGVCFcsus.fasta_refmod.fasta -uncertain 50lib_myotragus_reads_clean_mapped_UGVCFcsus.fasta_uncertainty.fasta`) to the developer (alexander_herbig@eva.mpg.de).

Altternatively you could try MultiVCFAnalyzer which serves the same purpose but with extra options
