### ISSUE TITLE
Improve/Smarter Cleanup

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#124]
**Is your feature request related to a problem? Please describe.**
There are many 'redundant' BAM files left over after each step which are unnecessary, and lead to a large disk-space footprint.

Running the following command for example:

```bash
nextflow run nf-core/eager \
-profile singularity \
--reads '/projects1/users/fellows/nextflow/eager2/dev_testing/data/*/*_R{1,2}*fastq.gz' \
--pairedEnd \
--fasta '/projects1/users/fellows/nextflow/eager2/dev_testing/references/tannerella_forsythia_actual/Tannerella_forsythia_9212.fa' \
--outdir '/projects1/users/fellows/nextflow/eager2/dev_testing/eager2/01-actual_reference/tannerella_forsythia/Multiple' \
--name 'eager_nextflow_dev' \
--email fellows@shh.mpg.de \
--max_cpus 3 \
--max_mem 32G \
--skip_preseq \
--min_adap_overlap 1 \
--clip_readlength 30 \
--clip_min_read_quality 20 \
--bwaalnn 0.01 \
--bwalnl 32 \
--bam_discard_unmapped \
--bam_unmapped_type discard \
--dedupper dedup \
--dedup_all_merged \
-r 2.0.4
```
Has the following BAM files remaining in the specified output directory

```
fellows@mpi-cruncher5:/projects1/users/fellows/nextflow/eager2/dev_testing/eager2/01-actual_reference/tannerella_forsythia/Multiple$ find -L -not -path work/ -name '*.bam' -type f | grep -v work
./deduplication/dedup/ABM006.A0101_S0_L004_R1_001.sorted.bam.filtered.sorted.bam
./samtools/filter/ABM006.A0101_S0_L004_R1_001.sorted.bam.filtered.bam
./mapping/bwa/ABM006.A0101_S0_L004_R1_001.sorted.bam

```
In principle there is no reason that I can think of why you would want the pre-dedup BAM files. 

Additionally, if there is a BAM file at the end of the pipeline, it might be worth also removing the post-AdapterRemoval fastq files.

**Describe the solution you'd like**

By default remove all the but the last produced BAM file. By this I mean if you have mapping/samtools filter/deduplication modules all turned on, keep only the deduplicated BAM. Whereas if deduplication is turned off, keep just samtools filter BAM, and remove mapping BAM.

One could also consider having an option to retain the 'earlier' BAMs, and the post-adapterremoval fastqs.

e.g.
```
--retain_adapterremoval_fastqs    retains output FASTQ files from AdapterRemoval

--retain_bam_file <module>          retains output BAM a particular module. Multiple modules can be specified by a comma separated list.  By default all but the last BAM file is removed.  Options are: mapping,samtools_filter.
```

**Additional context**
My justification is that the pipeline already can produce a lot of output files, and I think particular when dealing with novice users, it makes more sense to keep the output as slim as possible, to prevent unnecessary clutter because of people not checking every output folder after each run.

**Comment by apeltzer** [comment]
I agree - keeping the "last" part is a bit trickier to configure, but its possible and also easy to add the required params to the pipeline in a separate step, too.

**Comment by jfy133** [comment]
Would it not just requiring having an internal hierarchy to refer to, and checking which is the program highest up on that hierarchy that would be retained?

**Comment by apeltzer** [comment]
Yes, but how do I keep track of this is the problematic part - I'll think about it :-)

**Comment by jfy133** [comment]
Maybe ignore my hierarchy Idea. I agree that's more complicated.

I'm wondering if it possible to make it that the last command of a module runs successfully, it'll delete the input BAM (+csi)/FASTQ file (unless there is a param flag saying to keep it)?

The only thing is you would need to know which work directory the input came from. Is that possible?

**Comment by apeltzer** [comment]
Ok after giving this some more thoughts, it would be possible to use this approach:

- Add some flags for specific parts of the pipeline and by default just keep the last output (e.g. after dedup), making it configurable which BAMs for example are stored in the `results`folder

Then using the core nextflow function:

```
nextflow clean -help                                                                                                                                                                                               (multiqc-dev)
Clean up project cache and work directories
Usage: clean [options]
  Options:
    -after
       Clean up runs executed after the specified one
    -before
       Clean up runs executed before the specified one
    -but
       Clean up all runs except the specified one
    -n, -dry-run
       Print names of file to be removed without deleting them
       Default: false
    -f, -force
       Force clean command
       Default: false
    -h, -help
       Print the command usage
       Default: false
    -k, -keep-logs
       Removes only temporary files but retains execution log entries and
       metadata
       Default: false
    -q, -quiet
       Do not print names of files removed
       Default: false
```

That should be easy to do - can also make people do clean up using any of the above...

**Comment by apeltzer** [comment]
This is however on the level of execution runs (e.g. if you run the same workflow multiple times in the same directory, you can delete specific runs that were executed before/after etc). 

`nextflow clean -k` should already help a lot by deleting intermediate stuff - in combination with the output configuration to only keep intermediate data whenever this is desired should already suffice 👍

**Comment by jfy133** [comment]
I understand now I think, at least mostly. This would be the default clean up of everything in `work/` after transferring the final BAM to the publish directories, correct? But then you would have additional flags for somehow optionally transfering additional earlier FASTQ/BAM files? Let me know if I'm wrong.

How much work would this require? If it is quick to implement maybe it would be good for me to be able to play around with it to get a proper feeling for it to document it. I think it is good but it seems quite powerful and don't want people to make a mistake ;).

**Comment by apeltzer** [comment]
It's not that much work actually. We can potentially also implement support for creating/using CRAM instead of BAM, saving us another ~20% in data storage.

**Comment by jfy133** [comment]
Midnight thought: Would the cleanup happen if the run fails/hits an error?

BAM - CRAM, sounds good!

**Comment by apeltzer** [comment]
Cleanup can be triggered by the user afterward, e.g. happens only when desired ;-)

**Comment by jfy133** [comment]
Ah I see. Would need to make that very clear in the documentation though.

So you propose only adding post-DeDup bam to publishDir, unless other flags add the other things, and then the user 'manually' runs a cleanup after?

It'll certianly work to begin with.

**Comment by apeltzer** [comment]
Yes, that would be the first shot as it significantly gets the amount of data produced down.

**Comment by apeltzer** [comment]
Documentation is key here yes - without regularly cleaning work directories, this won't really help ...

**Comment by jfy133** [comment]
I think this is basically solved for the time being.

1. we explicitly say in the documentation to run the `nextflow clean` thing
2. As the new skip logic in PR #242 is so highly customisable, you won't have extra stuff you never request.
