### ISSUE TITLE
Add complexity filter?

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#13]
In our group we've noticed that we regularly get lots of poly G reads from NextSeq data which don't get discarded by the sequencer or demultiplexer. This can mess up some downstream statistics if not thrown out.

Maybe we could consider having as a module some form of complexity filter to remove low complexity reads?

**Comment by apeltzer** [comment]
Good idea - do you know any tool to be able to do/achieve that?

**Comment by jfy133** [comment]
PRINSEQ I believe

**Comment by jfy133** [comment]
Possibly a better (more recent) tool designed specifically for the case described above: https://github.com/OpenGene/fastp#polyg-tail-trimming

**Comment by apeltzer** [comment]
Fastp is really a nice tool. 

I'll add this before AdapterRemoval, keeping adapters and qualities untouched and only performing the poly_g_trimming on demand (default off, but people can turn it on if they want to!)

**Comment by apeltzer** [comment]
As of commit 24c33290d9a1fe50ab45e71777dd3d7e6f512b24 , this is implemented and also covered by test cases for both single end and paired end data.
