### ISSUE TITLE
BWA step fails on large genomes, because samtools index requires the "-c" (CSI index) flag

### ISSUE THREAD

**Issue by lucventurini** [nf-core/eager#146]
Observed while trialing the pipeline together with @hesterjvs on *H. vulgare*, with its genome over 4GBs.
The fix would be to add a "-c" flag to the samtools index command. However, this will result in the BAM file having a .csi, rather than .bai, index.
The analysis was done using the latest dev branch, with the Docker profile (revision: 435812b657 [dev]).

Key part of the log output:
```
ERROR ~ Error executing process > 'bwa (Sample_5_S5_L002_R1_001)'

Caused by:
  Process `bwa (Sample_5_S5_L002_R1_001)` terminated with an error exit status (1)

Command executed:

  bwa aln -t 8 bwa_index/*.fasta Sample_5_S5_L002_R1_001.combined.prefixed.fq.gz -n 0.04 -l 32 -k 2 -f "Sample_5_S5_L002_R1_001.combined.prefixed.fq.sai"
  bwa samse -r "@RG\tID:ILLUMINA-Sample_5_S5_L002_R1_001\tSM:Sample_5_S5_L002_R1_001\tPL:illumina" bwa_index/*.fasta "Sample_5_S5_L002_R1_001.combined.prefixed.fq".sai Sample_5_S5_L002_R1_001.combined.prefixed.fq.gz | samtools sort -@ 8 -O bam - > "Sample_5_S5_L002_R1_001".sorted.bam
  samtools index "Sample_5_S5_L002_R1_001".sorted.bam

Command exit status:
  1

Command output:
  (empty)

Command error:
  [bwa_aln] 17bp reads: max_diff = 2
  [bwa_aln] 38bp reads: max_diff = 3
  [bwa_aln] 64bp reads: max_diff = 4
  [bwa_aln] 93bp reads: max_diff = 5
  [bwa_aln] 124bp reads: max_diff = 6
  [bwa_aln] 157bp reads: max_diff = 7
  [bwa_aln] 190bp reads: max_diff = 8
  [bwa_aln] 225bp reads: max_diff = 9
  [bwa_aln_core] calculate SA coordinate... 37.53 sec
  [bwa_aln_core] write to the disk... 0.00 sec
  [bwa_aln_core] 7289 sequences have been processed.
  [main] Version: 0.7.17-r1188
  [main] CMD: bwa aln -t 8 -n 0.04 -l 32 -k 2 -f Sample_5_S5_L002_R1_001.combined.prefixed.fq.sai bwa_index/Hordeum_vulgare.IBSC_v2.dna.toplevel.fasta Sample_5_S5_L002_R1_001.combined.prefixed.fq.gz
  [main] Real time: 124.051 sec; CPU: 41.598 sec
  [bwa_aln_core] convert to sequence coordinate... 4.41 sec
  [bwa_aln_core] refine gapped alignments... 0.91 sec
  [bwa_aln_core] print alignments... 0.01 sec
  [bwa_aln_core] 7289 sequences have been processed.
  [main] Version: 0.7.17-r1188
  [main] CMD: bwa samse -r @RG\tID:ILLUMINA-Sample_5_S5_L002_R1_001\tSM:Sample_5_S5_L002_R1_001\tPL:illumina bwa_index/Hordeum_vulgare.IBSC_v2.dna.toplevel.fasta Sample_5_S5_L002_R1_001.combined.prefixed.fq.sai Sample_5_S5_L002_R1_001.combined.prefixed.fq.gz
  [main] Real time: 18.397 sec; CPU: 5.824 sec
  [bam_sort_core] merging from 0 files and 8 in-memory blocks...
  [E::hts_idx_push] Region 543480053..543480129 cannot be stored in a bai index. Try using a csi index with min_shift = 14, n_lvls >= 6
  samtools index: failed to create index for "Sample_5_S5_L002_R1_001.sorted.bam": Numerical result out of range
```

**Comment by apeltzer** [comment]
Ok you're really hitting borders that I never saw before here 👍 

Thanks for that, I'll see what we can do about it - should be an easy fix. Do you know by any chance whether I can use a CSI index for all kinds of references in general? That would make the indexing easier...

**Comment by apeltzer** [comment]
I fixed this in https://github.com/nf-core/eager/pull/147 , waiting for @jfy133 to review - if you#re keen you can also have a look, happy to have contributors in here too, can simply add you @lucventurini if you want to.

**Comment by jfy133** [comment]
Sorry to make it more complicated, but it might be safer for the moment to make this an option to turn on.

Java-based downstream tools like IGV remains shaky with CSI support (due to htsjdk): https://github.com/samtools/htsjdk/issues/1047

**Comment by apeltzer** [comment]
Hm, could also make it dependent on the input files size? e.g. if the genome size is > 4GB, I just run with the `-c` option, in the other case stay with the default? Would that help?

**Comment by jfy133** [comment]
Yes, that would be sufficient.

**Comment by apeltzer** [comment]
Did the changes in the updated PR - this automatically sets itself to using CSI indexing whenever a reference FastA file is larger than 3.5GB

**Comment by jfy133** [comment]
@lucventurini as we don't have a travis test for the `.csi` case (and I assume we can't set this one up because file sizes are too big, correct @apeltzer?), could you manually test that commit?

**Comment by apeltzer** [comment]
Would be possible to test this using this here:

```
nextflow run apeltzer/eager -r fix-samtools-idx [your_other_options]
```

**Comment by apeltzer** [comment]
Yes, @jfy133 we are in the process of getting bigger testcases set up, but for now we're bound to our smaller testcases ...

**Comment by lucventurini** [comment]
Hi all,
          thanks for the amazing bug fixing turnaround! @apeltzer , unfortunately in the past years I have been working with genomes far larger than barley ... it's a whole brave world over here, if you ever want to dip your toes :-)

I will be testing the pipeline immediately and report the result.

**Comment by apeltzer** [comment]
Happy when you are :-) 

We need more users with debugging feedback such as yours!

**Comment by lucventurini** [comment]
Hi @apeltzer , apologies, but 
```
nextflow run apeltzer/eager -r fix-samtools-idx [your_other_options]
```
fails on our machine. Specifically:

```
$ nextflow pull nf-core/eager -r fix-samtools-idx;
Checking nf-core/eager ...
Cannot find revision `fix-samtools-idx` -- Make sure that it exists in the remote repository `https://github.com/nf-core/eager`
(/software/stable/python/3.6.7/x86_64) luca@arsenal:/data/software/testing/eager/fix-samtools-idx/x86_64/bin$ nextflow run nf-core/eager -r fix-samtools-idx -profile docker "$@";
N E X T F L O W  ~  version 19.01.0
Cannot find revision `fix-samtools-idx` -- Make sure that it exists in the remote repository `https://github.com/nf-core/eager`
```

Is there anything specific I have to do to access the revision?

**Comment by apeltzer** [comment]
Yes, you need to use my own copy (which contains the potential fix):

```
nextflow pull apeltzer/eager ...
```

(you used `nextflow pull nf-core/eager`)

**Comment by lucventurini** [comment]
Hi @apeltzer , unfortunately the process failed again.
The line that needs changing is, specifically, line 666: we are using `bwa samse/sampe` rather than `bwa mem` for our analysis (that's the recommendation from an affiliated group).
Apologies for not having specified it earlier!

Likewise, I suspect that every time `samtools index` is invoked (which is quite a lot of times, looking at main.nf) we would need the `-c` switch to be present.

**Comment by lucventurini** [comment]
Hi @apeltzer ,
                       apologies for the bump, but might I ask whether you would have time to check this issue?
Alternatively, I think I can have a stab at fixing the issue myself, but I would have to ask you whether there is a guide about how to contribute to the project (aside from forking and issuing a pull request).

**Comment by apeltzer** [comment]
Hi @lucventurini !

In general, we're pretty open to any contributions - please fork, update what you think needs to be updated, add documentation and a changelog and let me or @jfy133 review it! 

I added the required changes and hope that my branch is now correctly doing the stuff you need - can you please use the new parameter `--large_ref`? 

```
nextflow pull apeltzer/eager
nextflow run apeltzer/eager -r fix-samtools-idx --large_ref [your_other_options]
```

Hopefully this should add the required `-c` switch - if not let me know or try fixing it in a PR - always happy to have contributors as I can only work in my spare time on this project now :-)

**Comment by lucventurini** [comment]
Hi @apeltzer ,
                       no problem, we will try it immediately! By the way, @hesterjvs and I think we got the reason that your changes were not functioning - we were passing in the FASTA file as a **symbolic link**, which has a negligible disk size. Eager did not follow the link to find the real genome file size ... and so thought the genome was minuscule.

Your `--large_ref` switch should solve the issue.

**Comment by apeltzer** [comment]
I just figured that this might be the case more often so I just thought adding another switch for users - most people will know about their chosen reference genome and additionally its documented now too, so should be fine to use then :-) 

Thanks for the hint! I didn't think about it and already wondered what caused the error but that makes sense !

**Comment by lucventurini** [comment]
Hi @apeltzer ,
                        that was definitely a wise decision! Unfortunately, we are still getting an error:
```
Feb-25 14:03:41.419 [Actor Thread 43] ERROR nextflow.processor.TaskProcessor - Error executing process > 'bwa (Sample_5_S5_L002_R1_001)'

Caused by:
  No signature of method: _nf_script_577c66c0.$() is applicable for argument types: (_nf_script_577c66c0$_run_closure32$_closure95$_closure96) values: [_nf_script_577c66c0$_run_closure32$_closure95$_closure96@61968e41]
Possible solutions: is(java.lang.Object), run(), run(), any(), tap(groovy.lang.Closure), use([Ljava.lang.Object;)

Source block:
  prefix = reads[0].toString() - ~/(_R1)?(\.combined\.)?(prefixed)?(_trimmed)?(_val_1)?(\.fq)?(\.fastq)?(\.gz)?$/
  fasta = "${index}/*.fasta" 
  size = ${params.large_ref} ? '-c' : ''
  """ 
  bwa aln -t ${task.cpus} $fasta $reads -n ${params.bwaalnn} -l ${params.bwaalnl} -k ${params.bwaalnk} -f "${reads.baseName}.sai"
  bwa samse -r "@RG\\tID:ILLUMINA-${prefix}\\tSM:${prefix}\\tPL:illumina" $fasta "${reads.baseName}".sai $reads | samtools sort -@ ${task.cpus} -O bam - > "${prefix}".sorted.bam
  samtools index $size "${prefix}".sorted.bam
  """
```

I am not fluent in NextFlow or Groovy, so this error is a bit incomprehinsible for me.

**Comment by apeltzer** [comment]
Can you pull once more? I had that in the beginning too but changed it to have proper variable substitutions in the script afterwards :+1:

**Comment by hesterjvs** [comment]
Hi @apeltzer ,
thanks for prompt responses to fix the problems @lucventurini and I run into! At this stage the pipeline finishes, but from qualimap, AFAICS onwards, it just processes one file. When I repeat it with `-resume` another one will be processed. Any idea on what goes wrong here?

**Comment by jfy133** [comment]
Hi Hester, this was also reported in issue #140, and a fix is waiting for final merging by Alex once he's finished his conference!

**Comment by apeltzer** [comment]
Ok, merged the PR in and will take care of the other qualimap issue / and look into it, reporting back in the #140 issue ticket for that one 👍

**Comment by lucventurini** [comment]
Thanks @apeltzer! We will wait regarding #140, please let us know if we can be of any help.

**Comment by apeltzer** [comment]
Hi @lucventurini ! You may try running `-r dev` now, containing fixes for all the issues you experienced. Let me know if that resolved the problems 👍
