### ISSUE TITLE
Only a single dedup.log file is exported to final deduplication/dedup directory

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#154]
**Describe the bug**
Presumably due to having the same name, only a single `dedup.log` file is present in the `deduplication/dedup` output directory. Note that the `.hist` files are correctly there for every sample. Just the `.log` is not.

**To Reproduce**
Run a pipeline (`-r dev`) with DeDup included. 

**Expected behavior**
A `dedup.log` file is presented for every sample

**Comment by apeltzer** [comment]
Ah that should be an easy fix .... its just not yet published the file, they're all there. Never thought anybody wants them to be able to see them ;-)

**Comment by jfy133** [comment]
Yeah exactly, they are in `work/*` but I have a feeling when 'publishing' them to the main output directory each one overwrites the other. If that's what you mean.

Me neither, very much an edge case when trying to fix the DamageProfiler/Qualimap issue from 2.0.5, and I re-ran MultiQC. Would never have had noticed otherwise :laughing:

**Comment by apeltzer** [comment]
Ah its not a problem to have multiple output folders based on sample names in the `$outdir` folder at all, can do that 👍
