### ISSUE TITLE
Option to skip FASTQC

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#182]
**Is your feature request related to a problem? Please describe.**
If you've already QCd your data and are e.g. remapping, you maybe do not want FastQC to be run again (particularly on already merged data).

An option should be offered to skip this step.

**Additional context**
It f'ing sucks when you have really deep data, and you're waiting for 4hrs for an unnecessary module ;)

**Comment by apeltzer** [comment]
Fixed in. https://github.com/nf-core/eager/pull/186
