### ISSUE TITLE
Post DeDup BAM files not published to correct publishDir

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#183]
**Describe the bug**
When running `2.0.7dev`, I noticed that the post-DeDup BAM files are not found in the correct final output DeDup directory.

The BAM files sit directly in `dedup/` rather than the specific sample directory that contains the `.log `and 
`.hist` files
**To Reproduce**
Run the pipeline with `DeDup` on.

**Expected behavior**

The post-DeDup bam to be published under: `deuplication/dedup/<SAMPLE>.filtered/<BAM_FILE>`

**Comment by apeltzer** [comment]
Ah but that was actually intentional by me - to keep the directory a bit cleaner, having the hist and log files only accessible in subdirs makes it a bit less crowded if running many samples at once.  Should I still change it?

**Comment by jfy133** [comment]
Mm ok. I personally would find it confusing (as I did), because if I see a
directory for a sample I expect everything related to that sample to be in
the same place.

I actually originally thought the bams weren't published, because when I
checked on my file browser all I saw were directories. As I had so many
samples I scrolled once or twice and didn't see anything else (should've
kept scrolling ;)) but still.

IMO organisation wise I think you should only have to look in one place for
all output of all samples so it is consistent. If it's in sample specific
directory then everything is that. If all samples are in a common
directory, then everything related to all the samples should also be there.

---
Sent my from my mobile
