### ISSUE TITLE
fastq metagenomics data file without human reads

### ISSUE THREAD

**Issue by ivelsko** [nf-core/eager#187]
Sometimes we don't have permission to work with human data that is part of our metagenomics sequencing data and we need to remove the human reads from fastq files before we can upload them to public databases like ENA. 

An additional feature that generates these human read-stripped fastq files would be very helpful to this end.

**Comment by jfy133** [comment]
Or alternatively (and maybe easier) is at least when running 'extractunmapped' is to provide a list of Read IDs of the _mapped_ file. So you can later go back to your raw-pre AR FASTQs and filter them out yourself.

**Comment by apeltzer** [comment]
The latter should be relatively straightforward.

**Comment by maxibor** [comment]
What about `samtools view -f 4 something.bam` ?

**Comment by apeltzer** [comment]
We already output the unmapped/mapped reads that way, but I think we should have a list of read IDs so that someone can directly remove these reads from a raw input file ...?

**Comment by maxibor** [comment]
or bedtools [bam2fastq](https://bedtools.readthedocs.io/en/latest/content/tools/bamtofastq.html) ?
I can get on that later today.

**Comment by apeltzer** [comment]
Yeah we do that already, but I think she wants to extract reads from the initial RAW FastQ file after analysis that are mapping to human, so to "anonymize" these files. Maybe I'm wrong :-D

**Comment by apeltzer** [comment]
Samtools can do bam2fastq meanwhile too 👍

**Comment by jfy133** [comment]
https://github.com/nf-core/eager/issues/187#issuecomment-481149776 correct!

**Comment by jfy133** [comment]
I've just reviewed how 'removal' of host DNA happens in other contexts and it seems it's not always stripped out but those particular reads are retained by rather masked with Ns. 

@ivelsko @apeltzer what is your experience in that, if any? @maxibor would it be feasible to change the new module to something like that? Or can `pysam` not do that easily?

I am just thinking this might make a bit more sense as I know some tools can complain if R1/R2s aren't in order or missing mates etc.

**Comment by apeltzer** [comment]
Done :-) 

We can still do that, but for now stripping means removing the reads entirely from the input data. As its done with the same IDs in both forward and reverse, this won't be causing issues with order or missing mates.
