### ISSUE TITLE
Fix reads in start log to also display readPaths

### ISSUE THREAD

**Issue by maxibor** [nf-core/eager#193]
Right now the eager start log only display the reads if `params.reads` is set.
When using `params.readPaths`, the start log doesn't display the reads used.

```
// Header log info
log.info "========================================="
log.info " nf-core/eager v${workflow.manifest.version}"
log.info "========================================="
def summary = [:]
summary['Pipeline Name']  = 'nf-core/eager'
summary['Pipeline Version'] = workflow.manifest.version
summary['Run Name']     = custom_runName ?: workflow.runName
summary['Reads']        = params.reads
```

**Comment by maxibor** [comment]
Waiting for #189 to be merged

**Comment by apeltzer** [comment]
Yeah but `readPaths` ist just used for tests as we can't use the glob pattern for URLs at the moment, so this is just missing in the travis CI tests which is fair to ignore it 👍
