### ISSUE TITLE
Non-GUI usage of EAGER pipeline [Feature]

### ISSUE THREAD

**Issue by EisenRa** [nf-core/eager#20]
Hiya,

While I think the GUI is great for people with little to no CLI experience, it can be a bit cumbersome for power-users. One useful feature for experienced users would be the ability to create .xml files in the CLI. This would be especially useful for people who don't have visualization technology on their servers to load the GUI.

Thanks!
Raphael

**Comment by apeltzer** [comment]
Sounds good! In that case, we'd have anyways the possibility to directly run using the CLI provided by Nextflow. That won't require an intermediate step - people can simply run such a CLI to process data directly.

**Comment by apeltzer** [comment]
Hi Raphael,

there will be a CLI (which is the first priority) and later a GUI for running the pipeline. I guess most people will be quite happy with the CLI, the GUI will just be an extra feature for later.
