### ISSUE TITLE
MultiQC Missing Plots and Filenames

### ISSUE THREAD

**Issue by ktmeaton** [nf-core/eager#218]
**Observed Bug**
Eager v2.0.6 might be missing some the MultiQC plots (ex. "FastQC (post-AdapterRemoval)" section) and the output plots for "FastQC (pre-AdadpterRemoval)" are chimeric of untrimmed R2 and merged R1.

**Suggested Fix**
I fixed this by editing conf/multiqc_config.yaml and replacing all instances of:
*.combined.prefixed_fastqc.zip
with
*.combined_fastqc.zip

**Explanation**
Perhaps there was a pipeline-wide renaming of the fastqc files that didn't get carried over to the multiqc configuration file? Thank you for your time!

**System**
- OS: Linux (Ubuntu 18.04.1 & CentOS 6.10)
- nf-core: eager v2.0.6
- installation method: conda

**Comment by apeltzer** [comment]
Hi Katie!

thanks for spotting this - we already fixed this in 2.0.7dev, I should probably put up a new release fixing these smaller errors. 

This here shows the changed version in 2.0.7dev at the moment:

https://github.com/nf-core/eager/blob/dev/assets/multiqc_config.yaml

You can try running that version using `-r dev` - it should do the same as your aforementioned fix?


I might have to put up a new 2.0.7 release addressing some of these "smaller" points that we found in 2.0.6 before we hopefully work on incorporating all the other things in 2.1.X releases :+1

**Comment by apeltzer** [comment]
Would be great to get some more people involved here - the aim of the project is to make it work for as many people as possible, so I'm always super excited when new people join in this effort :-)

**Comment by ktmeaton** [comment]
The multiqc configuration on the dev branch works exactly as you described, thank you so much for your response and instructions!

**Comment by apeltzer** [comment]
Okay Perfect

**Comment by apeltzer** [comment]
I'll do a release the next days - I think we should have another minor release that fixes some of the most annoying issues we experienced with 2.0.6 fairly soon.
