### ISSUE TITLE
Supplying a bwa index produces only single sample output for mapping

### ISSUE THREAD

**Issue by ktmeaton** [nf-core/eager#219]
**Describe the bug**
Hi EAGER team, the -r dev branch appears to have strange behavior when supplying a bwa index. Multi-sample runs behave as expected through trimming and merging but for mapping and downstream tools only one sample is processed before it finishes. I haven't been able to figure this out so if you have this resolved this or if it's a misunderstanding of usage on my part that would be great to know!

In this example, there are 3 paired-end libraries TestData01, TestData02, and TestData03. Only TestData02 runs through bwa and subsequent steps.

[warm up] executor > local
[3d/68dca2] Submitted process > makeSeqDict (Enterobacteria_phage_lambda.fasta)
[e1/fd8ece] Submitted process > fastqc (TestData01)
[15/f40e74] Submitted process > fastqc (TestData02)
[cd/de2157] Submitted process > fastqc (TestData03)
[95/cf6b08] Submitted process > adapter_removal (TestData02)
[d5/0e17b6] Submitted process > adapter_removal (TestData03)
[af/5e7530] Submitted process > adapter_removal (TestData01)
[2f/cb712f] Submitted process > output_documentation
[71/60e771] Submitted process > fastqc_after_clipping (TestData02.pass_1.fastq)
[ed/b567d4] Submitted process > bwa (TestData02.pass_1.fastq)
[8e/be6de0] Submitted process > fastqc_after_clipping (TestData03.pass_1.fastq)
[66/dcb279] Submitted process > fastqc_after_clipping (TestData01.pass_1.fastq)
[cb/d83538] Submitted process > samtools_idxstats (TestData02.pass_1.fastq.combined.fq.sorted)
[85/7f3264] Submitted process > damageprofiler (TestData02.pass_1.fastq.combined.fq.sorted)
[a1/61e362] Submitted process > samtools_filter (TestData02.pass_1.fastq.combined.fq.sorted.bam)
[8b/109241] Submitted process > qualimap (TestData02.pass_1.fastq.combined.fq.sorted.bam.filtered)
[55/6b513b] Submitted process > dedup (TestData02.pass_1.fastq.combined.fq.sorted.bam.filtered)
[8b/c327d5] Submitted process > get_software_versions (1)
[e9/38c8dd] Submitted process > preseq (TestData02.pass_1.fastq.combined.fq.sorted.bam.filtered)
[15/2bc362] Submitted process > multiqc
Warning, pipeline completed, but with errored process(es)
Number of ignored errored process(es) : 0 
Number of successfully ran process(es) : 20 
[nf-core/eager]Pipeline completed successfully

**To Reproduce**
Steps to make me able to reproduce the behavior:
1. The pipeline command causing the problematic behavior is included in the file:  [command_test_devIndex.txt](https://github.com/nf-core/eager/files/3267759/command_test_devIndex.txt)
2. Functionality can be rescued by either removing the parameter --bwa_index, or by running the pipeline with the -r master branch and then resetting the --bwa_index to the reference directory.

**Expected behavior**
In the test case, I would expect the remaining three files (TestData01 and TestData03) to also complete mapping, qualimap, dedup, etc.) since this is what happens in the master branch or without a bwa index supplied.

**Operating System:**
 - OS: CentOS 6.10
 - nf-core/eager revision: 59fbcc1007 [dev]

**Additional Files**
[devIndex.nextflow.log](https://github.com/nf-core/eager/files/3267777/devIndex.nextflow.log)

Thank you!

**Comment by apeltzer** [comment]
This is a bug. I'll have a look and will hopefully have a solution before going on vacation these days 😓

**Comment by drpatelh** [comment]
https://github.com/nf-core/chipseq/blob/333bba334512625775157aa0087c023cf0bde397/main.nf#L548

A `collect()` should do it @apeltzer

**Comment by ktmeaton** [comment]
At least for _bwa aln_ and my test cases, adding the collect() function fixes it!

**Comment by apeltzer** [comment]
This should be addressed in https://github.com/nf-core/eager/pull/221
