### ISSUE TITLE
Update AdapterRemoval with skip 5prime trimming

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#226]
The latest version of [AdapterRemoval](https://github.com/MikkelSchubert/adapterremoval) now has a new flag related to issues identified with erroneous trimming of 5 prime ends leading to true PCR duplicates not being removed. 

We need to 

a) bump the AR version in the environment
b) add the [`--preserve5p`](https://github.com/MikkelSchubert/adapterremoval/issues/32) flag to EAGER2 options

**Comment by jfy133** [comment]
And thanks @maxibor for the reminder to post this ;)

**Comment by apeltzer** [comment]
Yeah given that the bioconda recipe is already updated, we could probably push this in very quickly!

**Comment by jfy133** [comment]
Added in https://github.com/nf-core/eager/pull/255
