### ISSUE TITLE
MultiQC reports post-samtools filtering stats file info

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#230]
**Describe the bug**
MultiQC only includes in it's report the post-samtools filtering stats file, the pre-filtering information is lost.

**To Reproduce**
Run `-r 2.0.7` with map quality filtering, and look in `MultiQC/<your_run>_multiqc_report_data/` for 
`multiqc_samtoolsflagstat.txt`. You should only see entries for post-filtering, as they do not have hte `truncated.sorted.bam.filtered.stats` extension which distinguish them from the pre-quality filtering samtools stats files. 

Note that all the expected files are in `samtools/stats`, this issue is restricted to multiQC

**Comment by apeltzer** [comment]
Hm, one could add an extra section (as is done for FastQC in some pipelines) to have this in both cases, e.g. once pre-filtering, once post-filtering. Need to check if this is possible, at least for FastQC I think it is, so should be possible to do something about it here too...

**Comment by drpatelh** [comment]
It sure is :smile: 
https://github.com/nf-core/chipseq/blob/master/assets/multiqc/multiqc_config.yaml

**Comment by apeltzer** [comment]
Ah, love this community putting even links in to code pieces you need 💯

**Comment by jfy133** [comment]
It was technically working. But was sometimes failing due to BAM file names suffixes not being consistent so files weren't being picked up always. Fixed in PR #296
