### ISSUE TITLE
Investigate usage of blanks

### ISSUE THREAD

**Issue by apeltzer** [nf-core/eager#244]
Some approaches in medical genomics use the blanks to subtract the data sequenced there from the actual samples to remove background noise. Something we should also consider and could easily add (at least optionally!)

**Comment by jfy133** [comment]
You mean actual reads? Or in terms of metagenomics?

In the case of the latter, there is this method: Davis, N.M. et al., 2018. Simple statistical identification and removal of contaminant sequences in marker-gene and metagenomics data. Microbiome, 6(1), p.226. Available at: https://doi.org/10.1186/s40168-018-0605-2.

Which is quite nice. Based on the idea that lab contaminants (OTU/microbial species) are inversely correlated with DNA yield (i.e. the greater the DNA of the sample, the lower the signal of the contaminant - which presumable as an uniform background level in the lab). 

It requires DNA yield info (qPCR typically), so would be another nice case for TSV input, an d assuming we add metagenomic modules.

**Comment by jfy133** [comment]
Given genomics I haven't yet seen an implementation of this concept yet, and metagenomics there are better workflows this would be applicable for (taxprofiler), I'm going close this
