### ISSUE TITLE
Add metagenomics module

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#249]
**Is your feature request related to a problem? Please describe.**
A standard step of ancient metagenomics work (pathogens, microbiome), is now performing a metagenomic screening i.e. rapid/approximate alignment against a reference database of many genomes at once - typically on the off-target reads of the original host (e.g. host is human, but want to look what bacterial infection killed the person). It would be another good end point of EAGER is a basic OTU table (and some summaries), as initial microbial composition check before downstream analysis outside the scope of EAGER.

This would also be a nice upgrade from EAGER1, for any future publication as it brings EAGER up-to-date with the current state of the aDNA field.

**Describe the solution you'd like**
Add meta-genomic module.

Suggestions:
- HOPS Pipeline (currently requires a slight modification to the conda recipe to make malt-extract accessible via a environment variable)
- Kraken (@maxibor - would need your input here)

**Other things to consider**
MALT (used in HOPS) often requires a large amount of MEM/CPUs depending on the database. How to specify this/warn the user?

**Comment by apeltzer** [comment]
All in V2.1? :-D

**Comment by jfy133** [comment]
HOPS certainly. It'll be straight forward once Ron has updated the HOPS recipe.

**Comment by jfy133** [comment]
https://github.com/nf-core/eager/pull/284

**Comment by apeltzer** [comment]
All there in `dev`, coming with 2.1.0 !

**Comment by jfy133** [comment]
Re-opening after reconsideration of adding Kraken with @maxibor , which is more accesible tool to wider labs and is pretty commonly used now.

**Comment by maxibor** [comment]
Kraken PR with #355

**Comment by jfy133** [comment]
Thanks @maxibor !
