### ISSUE TITLE
Improve test datasets/commands

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#259]
**Describe the bug**

Currently, many of the BAM as input tests in travis do not work properly (https://travis-ci.com/nf-core/eager/jobs/248050239). This may be related to recent logic changes, and the old travis test not working properly (e.g. now don't by default convert BAM back to FASTQ, so a BAM + adapterRemoval test didn't work properly).

While this isn't a main functionality for EAGER, it is useful in some cases so we should check it does work.

Will work on this with @TCLamnidis

**Comment by tbugfinder** [comment]
Hi,
is that the reason why the execution based on the test profile is failing?


```
[0;35m[nf-core/eager] Pipeline completed with errors
[ad/156166] NOTE: Missing output file(s) `*_fastqc.{zip,html}` expected by process `fastqc (JK2782_TGGCCGATCAACGA_L008)` -- Error is ignored
[1b/92c638] NOTE: Missing output file(s) `*_fastqc.{zip,html}` expected by process `fastqc (JK2785_TGGCCGATCAACGA_L008)` -- Error is ignored
Error executing process > 'makeFastaIndex (Mammoth_MT_Krause.fasta)'

Caused by:
  Process `makeFastaIndex (Mammoth_MT_Krause.fasta)` terminated with an error exit status (1)

Command executed:

  samtools faidx Mammoth_MT_Krause.fasta

Command exit status:
  1

Command output:
  (empty)

Command error:
  [E::fai_build3_core] Failed to open the file Mammoth_MT_Krause.fasta
  [faidx] Could not build fai index Mammoth_MT_Krause.fasta.fai


```

**Comment by jfy133** [comment]
In this case, no that shouldn't be the case as the issues I'm referring to above is specifically related to the BAM input files.

In the error you provide above, the error is referring to the reference file is not being found. Could you provide the nextflow command you used when this error occured?

**Comment by tbugfinder** [comment]
Just the test command: `nextflow run nf-core/eager -profile singularity,test --pairedEnd`

**Comment by jfy133** [comment]
Hm strange, when I try it (albeit with a different profile because our singularity is set up a bit wierdly), it runs for me fine?

What version of nextflow are using? Have you pulled the latest version of EAGER?

```
fellows@mpi-sdag1:/projects1/users/fellows/nextflow/eager2/test$ nextflow run nf-core/eager -profile test,shh --pairedEnd -r master
N E X T F L O W  ~  version 19.04.1
Launching `nf-core/eager` [small_hopper] - revision: b8d3dec3f0 [master]
[2m----------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/eager v2.0.7
----------------------------------------------------
Pipeline Name     : nf-core/eager
Pipeline Version  : 2.0.7
Run Name          : small_hopper
Reads             : data/*{1,2}.fastq.gz
Fasta Ref         : https://raw.githubusercontent.com/nf-core/test-datasets/eager2/reference/Mammoth_MT_Krause.fasta
BAM Index Type    : CSI
Data Type         : Paired-End
Skip Collapsing   : No
Skip Trimming     : No
Output stripped fastq: No
Max Memory        : 6 GB
Max CPUs          : 2
Max Time          : 2d
Output dir        : ./results
Working dir       : /projects1/users/fellows/nextflow/eager2/test/work
Container Engine  : singularity
Container         : nfcore/eager:2.0.7
Current home      : /projects1/clusterhomes/fellows
Current user      : fellows
Current path      : /projects1/users/fellows/nextflow/eager2/test
Script dir        : /projects1/clusterhomes/fellows/.nextflow/assets/nf-core/eager
Config Profile    : test,shh
Config Description: Minimal test dataset to check pipeline function
Config Contact    : James Fellows Yates (@jfy133)
Config URL        : https://shh.mpg.de
[2m----------------------------------------------------
[warm up] executor > slurm
executor >  slurm (12)
[81/b3b0ab] process > makeSeqDict           [100%] 1 of 1 ✔
[92/304f90] process > makeBWAIndex          [100%] 1 of 1 ✔
[84/9ff4b6] process > makeFastaIndex        [100%] 1 of 1 ✔
[a2/d08114] process > output_documentation  [100%] 1 of 1 ✔
[14/2d0b7d] process > fastqc                [100%] 2 of 2 ✔
[0e/67ecb0] process > adapter_removal       [100%] 2 of 2 ✔
[11/1c2035] process > fastqc_after_clipping [100%] 2 of 2 ✔
```

If this still doesn't work you could try the test command but with `-r dev` to try our beta version - which  should work (as I've run this on our cluseter and passed the automated travis tests here on GitHub)

**Comment by tbugfinder** [comment]
I'd updated to NXF edge
```
$ ~/bin/nextflow -v
nextflow version 19.09.0-edge.5167
```

Eager is also master.

I found this error:
```
         "commitId": "b8d3dec3f044da5ec016493108910945be2b8702",
         "errorMessage": "Loading required package: markdown\nInstalling package into \u2018/usr/lib64/R/library\u2019\n(as \u2018lib\u2019 is unspecified)\nWarning in install.packages(\"markdown\", dependencies = TRUE, repos = \"http://cloud.r-project.org/\") :\n  'lib = \"/usr/lib64/R/library\"' is not writable\nError in install.packages(\"markdown\", dependencies = TRUE, repos = \"http://cloud.r-project.org/\") : \n  unable to install packages\nIn addition: Warning message:\nIn library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :\n  there is no package called \u2018markdown\u2019\nExecution halted",

```

and
```
         "errorReport": "Error executing process > 'output_documentation'\n\nCaused by:\n  Process `output_documentation` terminated with an error exit status (1)\n\nCommand executed:\n\n  markdown_to_html.r output.md results_description.html\n\nCommand exit status:\n  1\n\nCommand output:\n  (empty)\n\nCommand error:\n  Loading required package: markdown\n  Installing package into \u2018/usr/lib64/R/library\u2019\n  (as \u2018lib\u2019 is unspecified)\n  Warning in install.packages(\"markdown\", dependencies = TRUE, repos = \"http://cloud.r-project.org/\") :\n    'lib = \"/usr/lib64/R/library\"' is not writable\n  Error in install.packages(\"markdown\", dependencies = TRUE, repos = \"http://cloud.r-project.org/\") : \n    unable to install packages\n  In addition: Warning message:\n  In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :\n    there is no package called \u2018markdown\u2019\n  Execution halted\n\nWork dir:\n
```

I'm not root user.

**Comment by jfy133** [comment]
@apeltzer do you have any idea?

I guess the only other thing I can think is trying the last stable version of nextflow (assuming you were using edge for the original error), and running with the eager `dev` branch to see if there is a difference there? I'm not that familiar with nextflow itself yet unfortunately.

**Comment by apeltzer** [comment]
19.10.0 is out - maybe try that and then report back whether the error is gone? 

Otherwise I'll have a more detailed look at this!

**Comment by jfy133** [comment]
Could you also confirm OS?

I'll be setting up nextflow/eager fresh for a colleague in Friday, on a
brand new Ubuntu install, so I can see if the same issue is there.

Cheers,

---
Sent my from my mobile

**Comment by tbugfinder** [comment]
It's CentOS7.4

**Comment by tbugfinder** [comment]
I'Ve updated to 19.10.0 - error is still there.

**Comment by tbugfinder** [comment]
again, I think it tries to install markdown:
```
work/3d/605758d2610a39ee1c598004c621a3/.command.err:Error in install.packages("markdown", dependencies = TRUE, repos = "http://cloud.r-project.org/") :
work/3d/605758d2610a39ee1c598004c621a3/.command.err:  there is no package called ‘markdown’
work/3d/605758d2610a39ee1c598004c621a3/.command.log:Loading required package: markdown
work/3d/605758d2610a39ee1c598004c621a3/.command.log:Warning in install.packages("markdown", dependencies = TRUE, repos = "http://cloud.r-project.org/") :
work/3d/605758d2610a39ee1c598004c621a3/.command.log:Error in install.packages("markdown", dependencies = TRUE, repos = "http://cloud.r-project.org/") :
work/3d/605758d2610a39ee1c598004c621a3/.command.log:  there is no package called ‘markdown’
work/a0/2435920f9aa346464d854c592b37d5/.command.sh:markdown_to_html.r output.md results_description.html
work/a0/2435920f9aa346464d854c592b37d5/.command.err:Loading required package: markdown

```

**Comment by tbugfinder** [comment]
If I run this https://github.com/nf-core/eager/blob/master/bin/markdown_to_html.r#L13 command in a shell, I get:
```
> install.packages("markdown", dependencies=TRUE, repos='http://cloud.r-project.org/')
Installing package into ‘/usr/lib64/R/library’
(as ‘lib’ is unspecified)
Warning in install.packages("markdown", dependencies = TRUE, repos = "http://cloud.r-project.org/") :
  'lib = "/usr/lib64/R/library"' is not writable
Would you like to use a personal library instead?  (y/n)

```

**Comment by tbugfinder** [comment]
Should the install.packages command specify a proper lib path?
```
> .libPaths()
[1] "/usr/lib64/R/library" "/usr/share/R/library"
>
```

**Comment by jfy133** [comment]
Could you try switching the order of your command to `-profile test,singularity` (reverse of what you have above)?

If nextflow is trying to install stuff that would suggest to me the singularity container has not been found or not loaded. Everything should be already configured in the container so 'installing' stuff shouldn't be required (@apeltzer, is my understanding correct?)

**Comment by tbugfinder** [comment]
The order doesn't change anything.

**Comment by jfy133** [comment]
Ah ok.

Could you please make a zip of the whole log file and upload here?

**Comment by tbugfinder** [comment]
This piece of code doesn't make sense.
It deletes the file being within the workdir and then tries to create the link there.

```
nxf_stage() {
    true
    # stage input files
    rm -f Mammoth_MT_Krause.fasta
    rm -f where_are_my_files.txt
    ln -s /scratch/ec2-user/nextflow/work/stage/d6/f69d5d13625445e2d52c18d8ef1368/Mammoth_MT_Krause.fasta Mammoth_MT_Krause.fasta
    ln -s /home/ec2-user/.nextflow/assets/nf-core/eager/assets/where_are_my_files.txt where_are_my_files.txt
}

```

Will add logs.

**Comment by jfy133** [comment]
Those commands doesn't occur in the the EAGER code, so I assume it's an issue with your instance not being able to find the reference file described in the test profile (for whatever reason), and therefore nextflow itself is failing for some reason, I guess?
 
The reference files are hosted [online](https://raw.githubusercontent.com/nf-core/test-datasets/eager2/reference) (which is where the test profile points) so should be downloaded as first step by nextflow.

I think we are getting closer to the issue now, so logs would help confirm this.

**Comment by tbugfinder** [comment]
Running it using docker is ok, running using singularity failed.

**Comment by tbugfinder** [comment]
[eager-error.tar.gz](https://github.com/nf-core/eager/files/3764157/eager-error.tar.gz)

**Comment by apeltzer** [comment]
Ahem

**Comment by apeltzer** [comment]
https://nf-co.re/usage/troubleshooting#cannot-find-input-files-when-using-singularity

**Comment by tbugfinder** [comment]
Somehow stupid, however docker also fails (now?).
I run `singularity shell` before and can access all those directories used.

**Comment by jfy133** [comment]
> Somehow stupid, however docker also fails (now?).
> I run `singularity shell` before and can access all those directories used.

Sorry, that was my bad. I accidently pushed some changes to the `nf-core/test-dataset` eager2 branch rather than making a PR. These have just now been reverted. The docker command should work again.

**Comment by tbugfinder** [comment]
Today - above issues are gone for singularity execution.

**Comment by jfy133** [comment]
Great! Just so that we are clear: we can consider your current issue solved?

**Comment by tbugfinder** [comment]
Yes, thx.

**Comment by jfy133** [comment]
Running notes

- [ ] Need to check if --convertBam is NOT on but with --bam, should not allow mapping step!
