### ISSUE TITLE
Prepare for nf-core sync

### ISSUE THREAD

**Issue by sven1103** [nf-core/eager#26]
In order to get synced with the nf-core template, this repo needs to be prepared accordingly as described in the [nf-core documentation](http://nf-co.re/sync).

**Comment by apeltzer** [comment]
I'm on it - template branch is there, will merge things today :-)

**Comment by apeltzer** [comment]
Merged it - now fixing remaining issues.

**Comment by apeltzer** [comment]
EAGER is in sync with nf-core/tools template now!
