### ISSUE TITLE
Update linting.... 

### ISSUE THREAD

**Issue by apeltzer** [nf-core/eager#265]
Requires some TLC:

**Comment by jfy133** [comment]
Very mysterious

**Comment by drpatelh** [comment]
Im not even prepared to take a wild guess :scream:

**Comment by apeltzer** [comment]
See https://github.com/nf-core/eager/pull/267 ;-) It was you @drpatelh that kind of pushed me to doing this now 😆

**Comment by drpatelh** [comment]
That would have been my wild guess :wink:
