### ISSUE TITLE
Transferring Travis CI to Github Actions

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#271]
@apeltzer  has already implemented this somewhat, but some further notes

# Point 1
nf-core now has tower.nf functionality with a public key. All nf-core test runs would go through the same account. Therefore all runs during CI needed to be pre-named, so we know which pipeline a run represents The tower key has been added to configs in `-r fixes-for-2.1.0` (now merged into dev) as well as job names, but this only covers travis. 

Job names are therefore needed to be added also github actions (`-name 'eager-XXXXX'`)

We will need to add to each job an env section to the yaml a generic job name for each job e.g. `$NAME` which includes `${GITHUB_REF##*/}` to specify branch name where the PR is coming fromm and, `"${GITHUB_ACTION}"` for the job/step ID (I think).

I propose something like this: 

```
env:
  TOWER_ACCESS_TOKEN="1c1f493bc2703472d6f1b9f6fb9e9d117abab7b1" 
  NAME: eager-${GITHUB_REF##*/}-${GITHUB_SHA:1:6}-${GITHUB_ACTION}

steps:
-name: basic test  
  run:
    nextflow run ${GITHUB_WORKSPACE} -profile test,docker -with-tower -name "$NAME-basic" ${{ matrix.endedness }} --saveReference

```

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables
https://stackoverflow.com/a/58034787

# Point 2
Because 19.04 doesn't have tower functionality, I think we shouldn't have both stable and latest releases of nextflow in the same job, but have this separately. Then we can customise `env:` accordingly. 

We could also maybe then stagger the job with https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idif (although I don't fully understand this yet. This would helpfully stop the suspected build crashes for testing UnifiedGenotyper download from having too many IPs downloading at once.

Alternatively we can have them in entirely separate workflows.

# Point 3

I don't think we should use the matrixes, as cool as they are, for turning modules on/off. The only 'safe' case I think we can do this is for running all 'terminal' steps i.e. output is not needed for another step (damageprofiler, qualimap etc). But this isn't that useful. I therefore suggest just transferring over the current travis commands.

I guess we _could_ use the actions for mutually exclusive parameters such as each different mapper, or genotyper etc.? 

# Misc
@apeltzer what is the current difference between the `ci` and `ci-extra` workflows?

**Comment by apeltzer** [comment]
I just created `ci` and `ci-extra` to have cleaner files and not everything in one large blob basically. 

Point 2: We can also bump to `19.10.0` which is stable and released too - not sure we really need to test with older Nextflow versions anyways. 

Point 1 is addressed already with your PR.

Point 3: We can drop matrices and instead just test regularly by porting everythign over to Github Actions - I like that.

**Comment by jfy133** [comment]
Ok, PR coming up!

**Comment by jfy133** [comment]
That said, with point 2 - it would still be good to have at least one stable nextflow version back (as people might not always be using latest and greatest) - to check for backwards compatibility. Do you know of an easy way of identifying this? (rather than one ahead as we had it before)
