### ISSUE TITLE
Move all `params.XYZ` to `nextflow.config`

### ISSUE THREAD

**Issue by apeltzer** [nf-core/eager#288]
As on the tin. 

We currently have *a lot* in the main, which shouldn't be the case. I'll probably clear this up with the TSV in a separate branch.

**Comment by jfy133** [comment]
Attempt in https://github.com/nf-core/eager/pull/289

**Comment by jfy133** [comment]
Noted a semi-redundent parameter: aligner vs mapper. Should consolidate before merge

**Comment by apeltzer** [comment]
All done, thanks James!
