### ISSUE TITLE
Support for snpAD

### ISSUE THREAD

**Issue by apeltzer** [nf-core/eager#29]
We should have support for snpAD, additionally incorporating mapability tracks if possible.

**Comment by jfy133** [comment]
Slight problem, not on conda and not github either :\

https://bioinf.eva.mpg.de/snpAD/. Dunno if they will allow that if (bio)conda can't verify stability of the lnk...

**Comment by sc13-bioinf** [comment]
I made a nextflow pipeline for snpAD so you can copy some of that if you want. The main reason my pipeline sucks is that it builds the substitution model for all chromosomes. You can just do that for one chromosome (or maybe X.Y.MT also if you really want) and then use that. Its in my HOMErepos/nextflow-snpAD but its not a git repo.

**Comment by jfy133** [comment]
Ok cool that would be really helpful! I was literally just thinking that as a roadmap that 2.3 could be under the theme 'Genotyoing Galore'. Can also add ANTCaller.

Once 2.2 is done we can plan that and look for other genotypers.

**Comment by jfy133** [comment]
AntCaller
https://link.springer.com/article/10.1007/s00438-017-1358-5

ARIADNA https://academic.oup.com/dnaresearch/article/25/6/619/5095197

**Comment by jfy133** [comment]
Closing in preference for: https://github.com/nf-core/eager/issues/451
