### ISSUE TITLE
VariantCalling / PseudoCalling Parallelization

### ISSUE THREAD

**Issue by apeltzer** [nf-core/eager#31]
Could be worth trying

splitBams -> genotype/pseudo-call/genotype likelihoods -> stitchVCFs together

**Comment by EisenRa** [comment]
The modern microbial genome mapping pipeline [SNIPPY](https://github.com/tseemann/snippy) parallelizes variant calling by chunking the reference ([lines 301](https://github.com/tseemann/snippy/blob/master/bin/snippy)). The variant caller it uses is FreeBayes.

**Comment by jfy133** [comment]
I will close this unless it is requested again. I think we in aDNA we rarely encounter high coverage mapping to very large genomes (like plants), so I think the benefits over just simple multi-threading of a given genotyper would be minimal in most cases.
