### ISSUE TITLE
Full iGenomes support

### ISSUE THREAD

**Issue by apeltzer** [nf-core/eager#312]
We should have full support for iGenomes. 
Please look at https://github.com/nf-core/rnaseq as an example (scrnaseq works and has less code), to look how to use iGenomes. That way, users could specify only available standardized reference genomes to use while still being able to use custom fasta/input files too.

**Comment by jfy133** [comment]
Updated https://github.com/jfy133/eager/commit/6441f2c0316f0026bcac466bac1e65efa8269089

This was actually implemented @apeltzer ;), I just added the one sanity check for the valid types of genomes avaliable.
