### ISSUE TITLE
CI: add output file checks

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#325]
**Is your feature request related to a problem? Please describe.**
 
Given complexity of the pipeline and conditional process logic, we should be a bit more detailed in our CI.

I suggest that after each step of GitHub actions, that we add a very simple check that the last step (I.e. a terminal process)/the process that the test step is testing, has a) the expected number of output files (i.e. a pattern matching e.g. $(readlink -f genotyping/*.vcf.gz | wc- l) and these are not empty with e.g.

```bash
If [[ -s <file> ]]]
```

Then we can detect when e.g. we have forgotten to `.collect() ` reference files, or that we haven't got a silent fail from a tool.

**Comment by apeltzer** [comment]
Thats a bit complicated to do to be honest 😓 Its almost like unit tests for the pipeline behaviour...

**Comment by jfy133** [comment]
Would it not just involve two more lines of bash in each step in githubactions??

**Comment by jfy133** [comment]
On second thoughts, it's not required by nf-core so will close for now.
