### ISSUE TITLE
Make input BAMs for nuclear contamination/sex det choosable

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#328]
**Is your feature request related to a problem? Please describe.**
Currently only DeDup'd level files go into nuclear contamination or sex det. However maybe a user would want a trimmed bam or PMD filtered BAM (latter less likely) into these analyses.

This should be made specifiable by the user as with genotyping.

**Comment by apeltzer** [comment]
Is this really a use case? i wonder how often this actually happens at all...

**Comment by jfy133** [comment]
Yeah still thinking about it. Might make a poll somewhere and ask.

I thought maybe for pmd at least, sex det only on damaged reads to reduce influence of possible contamination? But dunno.

**Comment by jfy133** [comment]
Polls says no :+1:
