### ISSUE TITLE
No pipeline crash if NF version too old

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#344]
**Describe the bug**
Pipeline doesn't crash if minimum version not reached. Nextflow tries anyway and gives uncomprehnsiable error for a new user.

See here: https://www.nextflow.io/docs/latest/metadata.html#nextflow-metadata

```
if( !nextflow.version.matches('0.22+') ) {
    println "This workflow requires Nextflow version 0.22 or greater -- You are running version $nextflow.version"
    exit 1
}
```

**Comment by apeltzer** [comment]
I thought that isn't possible when the manifest specifies a minimum version @pditommaso might know better?

**Comment by pditommaso** [comment]
it should stop when prefixing the version with `!`, see [here](https://www.nextflow.io/docs/latest/config.html?highlight=manifest#nextflow-version). Tho, there could be an issue in recent NF versions.

**Comment by jfy133** [comment]
I think the `!` should do it. I'll try that now.

**Comment by ewels** [comment]
Linting updated in https://github.com/nf-core/tools/pull/507

**Comment by jfy133** [comment]
I suggest we merge #345 until the new version of nf-core tools is released and I'll replace with the nextflow 'native' system.

**Comment by apeltzer** [comment]
Aligned with template now, closing this
