### ISSUE TITLE
Fasta file must be call .fasta

### ISSUE THREAD

**Issue by chriswyatt1** [nf-core/eager#354]
Running circular mapper: the genome file must be called genome.fasta.  genome.fa fails. 

I worked around by changing main.nf at line 762 and 788 to .fa, but I was not sure how to change this at the start of the main.nf (line 233-263) to allow all fasta endings.

Here is the code I ran:
`nextflow run eager/main.nf -with-singularity nf-core-eager-master-latest.simg --singleEnd --reads '*.fastq.gz' --fasta B_genome.fa -with-report -with-trace -bg -resume --skip_adapterremoval --circularmapper --circulartarget Belonogaster_juncea_W06_pgas`

And the Nextflow error:
`Error executing process > 'circularmapper (Belonogaster_aurata_trimmed)'

Caused by:
  Process `circularmapper (Belonogaster_aurata_trimmed)` terminated with an error exit status (1)

Command executed:

  bwa aln -t 4 B_genome_500.fasta Belonogaster_aurata_trimmed.fastq.gz -n 0.04 -l 32 -k 2 -f Belonogaster_aurata_trimmed.sai
  bwa samse -r "@RG\tID:ILLUMINA-Belonogaster_aurata_trimmed\tSM:Belonogaster_aurata_trimmed\tPL:illumina" B_genome_500.fasta Belonogaster_aurata_trimmed.sai Belonogaster_aurata_trimmed.fastq.gz > tmp.out
  realignsamfile -e 500 -i tmp.out -r B_genome.fa  
  samtools sort -@ 4 -O bam tmp_realigned.bam > "Belonogaster_aurata_trimmed".sorted.bam
  samtools index "-c" "Belonogaster_aurata_trimmed".sorted.bam

Command exit status:
  1
Command output:
  (empty)
Command error:
  [bwa_aln] 17bp reads: max_diff = 2
  [bwa_aln] 38bp reads: max_diff = 3
  [bwa_aln] 64bp reads: max_diff = 4
  [bwa_aln] 93bp reads: max_diff = 5
  [bwa_aln] 124bp reads: max_diff = 6
  [bwa_aln] 157bp reads: max_diff = 7
  [bwa_aln] 190bp reads: max_diff = 8
  [bwa_aln] 225bp reads: max_diff = 9
  [bwa_aln] fail to locate the index`

Maybe its easier to just change instruction to .fasta name only. Sorry, I couldn't work out how to fix this. Thanks, its a very helpful pipeline.

**Comment by jfy133** [comment]
Hi @chriswyatt1 

Thanks for the report! Firstly could you please try running with the current dev version (by adding `-r dev` to the command). There were a lot of fixes recently which might also solve the issue - including allowing both fa and fasta reference extensions

Secondly, can you try also making sure all paths and string parameters are in quotes, and see if that helps. For example your `--fasta` and `--circulartarget` parameters above don't have them.

Let us know if these solutions don't work.

Cheers,

**Comment by chriswyatt1** [comment]
Thanks @jfy133,

Yes, the fasta name issue is fixed on the dev version, thanks I didn't realise how to do this. I have also added the quotes.

Best,
