### ISSUE TITLE
2.1 update clean up notes

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#359]
# Authors

- [x] Update author list in license/docker file to all expected final publication coauthors
- [x] Syncronise README for authors/contributors
- [x] Syncronise Manifest in nextflow .configs
- [x] Update authors in in main.nf header

# MultiQC
- [x] MultiQC config missing software versions report placement (and check how this works)
- [ ] Add more File Cleanup Strings to MultiQC yaml to have samples merged if possible

# Main.nf
- [x] Example command is missing required fasta in help message in main.nf
- [x] Missing Kraken and endorS.py commands in get software versions process 

# Tests
- [x] Try to get GATK 3.5 GithubActions to work

# get_software_versions

- [x] Missing Kraken regex
- [x] Missing endorS.py regex

# PR Template
- [x] Add note saying added new tool - added to get_softeware_versions process and python script.

**Comment by apeltzer** [comment]
MultiQC is up to you now ;-) 

Main.nf example command update too - once we have that, we can release I guess.

**Comment by apeltzer** [comment]
Readme has full list now. Contributors are sorted alphabetically now too. 

The manifest file is too long for tower.nf if we keep it complete - I replaced it there with "the nf-core/eager community", same in the dockerfile. The main.nf refers to the readme on the webpage now too - I think this is fine for everyone 👍

**Comment by jfy133** [comment]
Will do remaining points, and will split authors Vs contributors - as discussed on slack.

Will also try get GATK 3.5 GitHub actions test to work but not important.

**Comment by jfy133** [comment]
Going to leave " Add more File Cleanup Strings to MultiQC yaml to have samples merged if possible" until 2.2

Will do a big overhaul of MultiQC stuff when 1.9 comes out as that will bring a lot of waited-upon functionality. TSV input will also make this much easier to standardise what we clip off.
