### ISSUE TITLE
Add PMDTools

### ISSUE THREAD

**Issue by apeltzer** [nf-core/eager#36]
PMDTools should be available in EAGER2

**Comment by apeltzer** [comment]
```
 Traceback (most recent call last):
    File "/opt/conda/envs/nf-core-eager-2.0dev/bin/pmdtools", line 273, in <module>
      for line in sys.stdin: 
    File "/opt/conda/envs/nf-core-eager-2.0dev/lib/python3.6/codecs.py", line 321, in decode
      (result, consumed) = self._buffer_decode(data, self.errors, final)
  UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

Work dir:
  /home/alex/IDEA/nf-core/eager/work/28/a3abb8fdd48d72b959343acaeb80c9

```

**Comment by apeltzer** [comment]
Looks to me like a Python2.7 -> Python3.6 issue to be honest.

**Comment by apeltzer** [comment]
https://stackoverflow.com/questions/12468179/unicodedecodeerror-utf8-codec-cant-decode-byte-0x9c

**Comment by apeltzer** [comment]
Probably needs a fix in Python3

**Comment by apeltzer** [comment]
http://python-notes.curiousefficiency.org/en/latest/python3/text_file_processing.html#files-in-an-ascii-compatible-encoding-best-effort-is-acceptable

**Comment by boulund** [comment]
I have a personal copy of PMDTools that I have translated to Python3. I have tried contacting the author about it because the license situation for the code is unclear, so I currently haven't made the code public.

**Comment by apeltzer** [comment]
Yes, I am, actually worked a bit with him on making it possible to run it on Python3 (see here: https://github.com/pontussk/PMDtools). You can check there whether your code runs well on Python3, the current version there seems not to work properly when used...

**Comment by boulund** [comment]
Ah, nice! I see a license was added 8 months ago! No need for me to hold back then. I think my version should run just fine in Python3, I used it myself about a year ago in Python 3.6. I'll come back here when/if I've had time to have a look at it.

**Comment by apeltzer** [comment]
https://github.com/pontussk/PMDtools/issues/6
