### ISSUE TITLE
stuck on revision: dev

### ISSUE THREAD

**Issue by hughcross** [nf-core/eager#385]
Hello, 

I am trying to run version 2.1.0 with singularity. I pulled the image:

```
singularity pull --name eager-2.1.0.img docker://nfcore/eager:2.1.0
```

Then ran the command on some test data of mine, but it gave me this message:

> Project `nf-core/eager` currently is sticked on revision: dev -- you need to specify explicitly a revision with the option `-r` to use it

So I tried to run the test with dev version:

```
nextflow run nf-core/eager -profile singularity,test --paired_end -r dev
```

But it then gave me a bunch of error messages regarding markdown_to_html.py

So, is version 2.1 not stable? Is the development version 2.2dev still in development and not yet ready? For my research group I would like to be able to have a stable version that they can use. As well, we would like to have the option to go back and use that version if a follow up run is necessary. 

Any help would be appreciated.

**Comment by jfy133** [comment]
Hi Hugh,

You sort of have a bunch of questions:

1. Yes, 2.1.0 is 'pretty' stable (as in, only had one minor bug report so far). `dev` (or 2.2.0dev) is not yet stable. 
2. To update EAGER, you should always to run `nextflow pull nf-core/eager -r 2.1.0` where `-r 2.1.0` defines the version you want to run. If you have pulled multiple versions (like you have here, previously with `dev`), you must always specify which version of the pipeline whenever running. This is good practise anyway for reproducibility.
3. The singularity container does _not_ contain the pipeline code itself, just the programs it uses. Nextflow will automatically download the right singularity version for you each time you use it, so you shouldn't have to ever use singuarlity (assuming singularity is set up properly). 
4. Note that each user will have their own version of nf-core/eager (as when doing `nextflow pull nf-core/eager` the pipeline code is stored under `~/.nextflow`). To ensure your research group uses the right version, you will need to get each of them to do the `nextflow pull nf-core/eager -r x.x.x` and `nextflow run -r x.x.x` combination. However you _can_ set up a common singularity cache for everyone, which can be specified with a custom profile. This is recommended as the singularity images can be GBs in size. You can do this e.g. with [nf-core/configs](https://github.com/nf-core/configs), which allows you to customise lots of parameters for each institutional server/cluster etc. If you're interested in setting one up, let us know and we can help you set this up for your group/cluster

Let me know if that answers your questions.

As a side note: I am writing an introductory tutorial to using nf-core/eager [here](http://www.jafy.eu/posts/2020/03/nf-core-eager-tutorial.md/). This starts right from the beginning with setting up nextflow and is aimed for people who want to just try nf-core/eager out (you're a bit more advanced as you're using singularity).

It's still in draft, but if you think it'll help with introducing it to your research group, if you feel free to email or message me on slack if you have feedback (like if there is stuff you think would be useful), and I'll add to it accordingly. It's also CC-BY so you can also take parts of it if you want.

**Comment by hughcross** [comment]
Hi James,

Thanks very much for all of that. I will go through and try to pull and run version 2.1. I would very much like to set up a common singularity for everyone in our group, because of space limits on our cluster and to better help students. I managed to do this with a conda eager install last year on our local server. We have now mainly moved to the national server, where Singularity is preferred. I will have a go and post an update tomorrow. 

Thank you also for the link to the tutorial. I will share with our group. 

cheers,
hugh

**Comment by apeltzer** [comment]
Hi Hugh,

if you run the pipeline on the same cluster and everyone has access to e.g. a shared folder, you can add your cluster configuration to: https://github.com/nf-core/configs

and define a singularity cache folder, e.g. as done in this config here:

https://github.com/nf-core/configs/blob/2300d5a9626a486c41248f751d22e39f1ae7e717/conf/cfc.config#L10

That would then make all users using the same configuration profile via e.g. `-profile otago-cluster` (just an example name) use this if they specify the same revision of the pipeline with `-r 2.1.0` for example.

**Comment by jfy133** [comment]
:+1: to Alex says - if you are planning on getting more stuck in with nf-core etc. (which would be great.!), we would highly recommend joining the slack space for nf-core, and also the #eager and #configs channels: https://nf-co.re/join. Then we can help you in more 'real time' (as well as from a wider pool of experts!).

**Comment by hughcross** [comment]
Thanks to you both. I will definitely join the Slack channels.

**Comment by hughcross** [comment]
Hi,

Just an update: I installed nf-core tools and then used the instructions [**here**](https://nf-co.re/tools#downloading-pipelines-for-offline-use) to download the eager2 and singularity container to run everything offline. I ran some tests with small data sets and it worked. I have not had anyone else in the group try this. The downloaded files are in a shared space; do I need to create a config file so others can use it? I will go ahead and have others try. In general, is it good to have custom config files for working on a server and/or sharing files. We have limited space on our servers so cannot afford to have everyone download their own version every time.

This is the command that worked:

```
NFCORE='/nesi/project/uoo02328/programs/Nextflow'

nextflow run ${NFCORE}/nf-core-eager-2.1.0/workflow/ \
  -profile singularity \
  -with-singularity ${NFCORE}/nf-core-eager-2.1.0/singularity-images/nf-core-eager-2.1.0.simg \
  --paired_end \
  --reads '/nesi/project/uoo02328/hugh/eager_tests/test1set/BP8MR*_R{1,2}_001.fastq.gz' \
  --fasta '/nesi/project/uoo02328/hugh/eager_tests/refs/rCRS_NC_012920.fasta' \
  --outdir '/nesi/project/uoo02328/hugh/offline_eager_tests/singTest_ol1' \
  --max_memory '64.GB' --max_cpus 8 -name 'eager_humanMT_singTest_ol1' \
  --max_time '8.h'
```

Thanks

**Comment by apeltzer** [comment]
Hi Hugh!

glad this worked without any issues 🎉 

> In general, is it good to have custom config files for working on a server and/or sharing files. We have limited space on our servers so cannot afford to have everyone download their own version every time.

In general its advisable, e.g. you could have a very simple config file that should already make your command a bit shorter. You could try that using the code below and then store the file to `your_analysis_platform.config` and then supply that instead using:

```
nextflow run ${NFCORE}/nf-core-eager-2.1.0/workflow/ \
  -c your_analysis_platform.config
  --paired_end \
  --reads '/nesi/project/uoo02328/hugh/eager_tests/test1set/BP8MR*_R{1,2}_001.fastq.gz' \
  --fasta '/nesi/project/uoo02328/hugh/eager_tests/refs/rCRS_NC_012920.fasta' \
  --outdir '/nesi/project/uoo02328/hugh/offline_eager_tests/singTest_ol1' \
```

```bash
//Profile config names for nf-core/configs
params {
  config_profile_description = 'YOUR CLUSTER NAME cluster profile provided by nf-core/configs.'
  config_profile_contact = 'Hugh Cross @hughcross)'
  config_profile_url = 'your_url'
}

singularity {
  enabled = true
  cacheDir = '/nesi/project/uoo02328/programs/Nextflow'/nf-core-eager-2.1.0/singularity-images/''
}


params {
  igenomes_ignore = TRUE
  max_memory = 64.GB
  max_cpus = 8
  max_time = 8.h
}
```

If others can access the path above for where you used the and this works, we could make it so generic that all images used by people on your cluster end all up in the same location, thus making the analysis both reproducible and as space efficient as possible :-) 

Note: After finishing the analysis, you could also clean up: https://github.com/nf-core/eager#quick-start (see the clean up section).

**Comment by hughcross** [comment]
Thanks for the config suggestions. I am getting something wrong. When I use the -c parameter, I get the error around the singularity cacheDir argument. I tried changing this line to:

```
cacheDir = "/nesi/project/uoo02328/programs/Nextflow/nf-core-eager-2.1.0/singularity-images/"
```
but in that case it tries to pull the image again, and just ends with errors.

I am also unsure about the config_profile_description line. Does that need to refer to a specific config file, or is it just profile information?

Sorry, I could not find anything in the documentation, and have tried searching the slack channel.

**Comment by jfy133** [comment]
Hey Hugh, maybe you could post on the slack channel what your profile looks like and we can continue from there. We are getting a bit off topic here I realise, so better to continue elsewhere!
