### ISSUE TITLE
Genotyping / Downstream Analysis ideas

### ISSUE THREAD

**Issue by apeltzer** [nf-core/eager#40]
The former way to do things in EAGER1.X was to use GATK to call variants on the preprocessed / filtered BAM files and then use that to recreate e.g. a consensus FastA for small genomes and/or create a VCF for downstream tools. 

There are nowadays however tools out there that can be used for downstream genotyping, aware of ancient DNA damage etc, for example [snpAD](https://bioinf.eva.mpg.de/snpAD/) and IIRC [angsd](http://www.popgen.dk/angsd/index.php/ANGSD) and [sequenceTools](https://github.com/stschiff/sequenceTools) that I'd rather like to rely on, as they are specifically designed for aDNA usage.

The learning curve for these is okayish, as I think that basic functionality as for example solely output for downstream analysis tools is required.

My plan for now is to incorporate some of the functionality of:

- snpAD
- ANGSD
- sequenceTools

Additionally, I'd love to incorporate:

- [GenCons](https://github.com/subwaystation/TOPAS)
- [READ](https://bitbucket.org/tguenther/read)

These changes are planned features for V2.1 of the pipeline, 2.0 will "just" provide functionality for preprocessing, QC and mapping using BWA for now.

**Comment by apeltzer** [comment]
@jfy133 @sc13-bioinf @JudithNeukamm

Any ideas/thoughts/complaints on this plan?

**Comment by apeltzer** [comment]
@eisenra might also want to comment on this one :-)

**Comment by jfy133** [comment]
Downstream, I currently don't have any other opinions. But do you mean to not include GATK at all? Or were you focusing on just the downstream steps (which you would turn off the dedicated genotyping step)

**Comment by jfy133** [comment]
MultiVCFAnalyzer (https://github.com/alexherbig/MultiVCFAnalyzer) - the new
version isn't yet avaliable but is coming soon.

No, HaplotypeCaller would be sufficient (and would add more pressure to at
least get rid of reliance on un-maintained tools ;))

**Comment by EisenRa** [comment]
I'm ambivalent about the variant callers tailored for ancient DNA, as from what I understand, they focus more on human genomes. They still could be useful for people working on ancient human DNA, but I would not be the person to ask.

I agree with James that having HaplotypeCaller would be good as it is well supported and has other tools that rely on its output. 

Another variant caller to consider is [FreeBayes](https://github.com/ekg/freebayes). It is quite popular, works well for both human and microbial genomes, and provides a well-annotated VCF file (can also do joint calling between samples). It is used in the [SNIPPY pipeline](https://github.com/tseemann/snippy), which focuses on modern bacterial genome variant calling.

**Comment by apeltzer** [comment]
Thanks everyone for their valuable thoughts and ideas. 
That means I will most likely implement something like this:

- GATK (HaplotypeCaller only, drop UnifiedGenotyper as its dropped by everyone else too)
- FreeBayes

That should be nice for pathogen / bacterial people :-) 
And additionally: 

- ANGSD
- snpAD 
- sequenceTools 

for our human genetics people. (Though they could also of course rely on GATK/FreeBayes if they want to)

**Comment by jfy133** [comment]
Note that we will have to package GATK 3.5, because past 3.6 (I think, possible v4), IndelRealigner has been removed. The latest systems in GATK are not really comaptible with short read data anymore.

**Comment by teepean** [comment]
The last version of 3.x series (3.8-1) still has IndelRealigner.

**Comment by apeltzer** [comment]
Current GATK PR contains: #238 

- UnifiedGenotyper (GATK 3.8.1)
- HaplotypeCaller (latest GATK4.X) 

Will probably add more ANGSD, snpAD, etc on-demand in a separate release.

**Comment by jfy133** [comment]
See closed #10 for GenConS.
