### ISSUE TITLE
BAM as input?

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#41]
**Is your feature request related to a problem? Please describe.**
Sometimes we receive/download only BAM files (e.g. see Slon et al. 2017 data on ENA), that we wish remap/reprocess in a different context. For example if the data is metagenomic, and we want to map to a particular bacterial genome. Currently we would have to manually re-convert the BAM to FASTQ, which leads to unnecessary data redundancy.  

**Describe the solution you'd like**
An option to provide BAM as an input, rather than FASTQ. One solution would with a -bam flag, which would (turn-off a clip/merge module? and then) pipe stdout from `samtools fastq` into the mapper itself.

**Describe alternatives you've considered**
One could just manually re-convert the BAM.

**Comment by apeltzer** [comment]
Yup, that sounds good! I guess having a step to run on BAM directly would be quite easy to establish...

**Comment by jfy133** [comment]
This may also require a skip adapter_removal step of some kind, in case you want to re-run already preprocessed data.

**Comment by apeltzer** [comment]
This is addressed in https://github.com/nf-core/eager/pull/129
