### ISSUE TITLE
Add Proper AWS Test Data

### ISSUE THREAD

**Issue by apeltzer** [nf-core/eager#418]
We should have a proper profile for running a nice exemplary test dataset, e.g. using links from [OAGR](https://www.oagr.org.au/) 

The current `awstests.yml` simply runs on AWS using the regular `test` profile. However, it would be nicer to add a test with larger data.

**Comment by jfy133** [comment]
For clarification: we just need an AWS specific test profile, with I guess some FTP links of public data?

Or should the downloading of this data happen as a separate step in the `awstests.yml`?

**Comment by apeltzer** [comment]
In the config would be nicest :-)

**Comment by jfy133** [comment]
Just proper pathogen to go :muscle:

**Comment by jfy133** [comment]
Pathogen screening wouldn't be run on AWS because too memory heavy (and exepsive), so will close this issue.
