### ISSUE TITLE
Check Testdata URLs

### ISSUE THREAD

**Issue by apeltzer** [nf-core/eager#424]
While Reviewing Sarek, I remembered that Maxime mentioned that we need to Check Github RAW userdata URLs. Maybe something we have to check in our testdatasets / tsvs that these are used properly.

**Comment by jfy133** [comment]
I'm setting up an AWS-megatest branch, will review all profiles then as I add the AWS-megatest profiles

**Comment by jfy133** [comment]
Done for the moment. Everything is some variant of `raw`.
