### ISSUE TITLE
Add fastq trimming functionality

### ISSUE THREAD

**Issue by aidaanva** [nf-core/eager#431]
Allow for the trimming at the fastq level to allow for a more stringent mapping. Programs that could be used are: FASTP (https://github.com/OpenGene/fastp#global-trimming) and FastX_trimmer (https://anaconda.org/bioconda/fastx_toolkit)

**Comment by apeltzer** [comment]
Please `fastp` if possible ;-) That is already implemented and could just be extended 👍

**Comment by jfy133** [comment]
Problem with FASTP is that it happens _before_ poly-G trimming. This might be OK as I suspect you would only need to do FASTQ trimming _after_ evaluating your libraries, so you would trim on a re-run of previously run data.

FASTQ trimming is not _commonly_ done in all aDNA fields, so pushing back 2.3 until can evaluate this fully.

**Comment by jfy133** [comment]
@aidaanva this is now avaliable when using BowTie2 (as I found it offers it integrated). As Bowtie2 is apparently slightly better (https://www.frontiersin.org/articles/10.3389/fevo.2020.00105/full), I think this would be sufficient. If you absolutely need this independently later on, please re-open this issue.

**Comment by aidaanva** [comment]
Does that mean that I need to use bowtie as a mapper? What about if you want to use bwa?

**Comment by meganemichel** [comment]
Add functionality for trimming damage/barcodes prior to mapping without requiring use of bowtie as the mapper. Currently it does not seem to be possible to trim damage/barcodes using bowtie and map with bwa in the same run. Instead this requires two separate eager runs.

**Comment by jfy133** [comment]
I'm still not convinced we need to add a whole new tool and process for this. Like I said above, BowTie2 already does trimming _and_ mapping for you (and performs better it seems!). 

In terms of damage, you would already have to have it run once to know how much damage to remove, but please see #632 for adapters - this will at least be implemented as this is a more important issue.

**Comment by jfy133** [comment]
Sorry, I just should say that of course you are both welcome to make a PR to add it if you really really think BT2 is not comaptible for your data.!
