### ISSUE TITLE
DamageProfier exits 0 even if no output files

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#434]
Workaround: make all DamageProfiler output (txt/pdf/json) `optional True`. Log is still created but just reports all reads as 0.

Will also report upstream.

**Comment by apeltzer** [comment]
Yeah clearly an upstream bug that needs to be fixed/adjusted maybe. Although reporting zeros everywhere shouldn't be a bug actually ... (?)

**Comment by jfy133** [comment]
No, it's not. But I'm wondering why it can't also produce all the output files with 0s anyway.

Maybe I'm being too MultiQC centric now (thinking a user might be confused why there aren't damage curves for their given sample...)
