### ISSUE TITLE
Unclear output doc figure for Samtools flagstat and add MALT/KRAKEN/MVA etc.

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#442]
Aida pointed out that the image by @ZandraFagernas for Samtools flagstat might be misleading.

Equal sequencing depth makes sense for screening or initial runs, but is not what would be needed for deep sequencing projects.

Secondly, mapped reads being equal of course would be _amazing_ but rarely encountered in real life.

We should consider making a caveat (e.g. asterisk saying that we are assuming the above, or when no _a priori_ knowledge of endogenous NDA content), or add extra panels.

**Comment by jfy133** [comment]
@ZandraFagernas 

Can you do the following:

- [ ] Flip pannel A and C
- [ ] Rephase 'new' panel A as: **In an ideal world** of equal sequencing pooling and equal endogenous DNA
- [ ] Rephrase 'new' panel C: This can be **OK** when unequal number of reads were requested per sample but equal endogenous DNA.
- [ ] Rephrase panel B: This is **standard** for initial _preservation screening_ of aDNA with equal sequencing pooling and variable endogenous DNA.

**Comment by jfy133** [comment]
Reference:
![image](https://user-images.githubusercontent.com/17950287/86130182-140e1b00-bae4-11ea-8448-ddafb1628346.png)

and you can rephrase to condense ifneeded

**Comment by jfy133** [comment]
@ZandraFagernas Also the following needs to be updatd:

![image](https://user-images.githubusercontent.com/17950287/87294035-72cf8d80-c503-11ea-8e55-ae07f0a145e5.png)

Whereby poop1_lane4_SE needs to merge with the other PE lanes (i.e. same time as the library above); this behaviour will be changing in an upcoming PR because it was too restrictive.

**Comment by jfy133** [comment]
@ZandraFagernas the same issue in the Samtools image above also is for FASTQC - Sequence Count regarding the uneeven sequencing. Could you tweak the phrasing make clear this is for initial sequencing

**Comment by apeltzer** [comment]
Is this fixed now?

**Comment by jfy133** [comment]
Yes!
