### ISSUE TITLE
Keep merged fastq from multiple lanes after AdapterRemoval 

### ISSUE THREAD

**Issue by paulayu** [nf-core/eager#454]
Currently the cleaned fastq files kept in AdapterRemoval output are all lane-separated, but keeping the merged clean fastq will help if we want to re-use the cleaned reads.

**Comment by jfy133** [comment]
Thanks He! I will look into it.

**Comment by jfy133** [comment]
(Accidental close, sorry!)

**Comment by jfy133** [comment]
Report from @aidaanva that I also forgot to publish the BAMs from the first BAM merging step
