### ISSUE TITLE
Genotyping with pileupcaller produces genotypes for a single sample 

### ISSUE THREAD

**Issue by TCLamnidis** [nf-core/eager#457]
I ran eager on the dev branch, using pileupcaller to genotype. The genotyping created a dataset for one of the two individuals. The other individual was not genotyped at all.

The input tsv is this:
[eager.test.tsv.txt](https://github.com/nf-core/eager/files/4754145/eager.test.tsv.txt)

There should either be two individuals in the dataset (preferred), or at least 2 datasets (one per individual) produced.

**Comment by TCLamnidis** [comment]
Command used:
`nextflow run nf-core/eager -r dev -profile shh --input eager.test.tsv -w /projects1/users/lamnidis/eager2.pileupcaller.test/work --outdir /projects1/users/lamnidis/eager2.pileupcaller.test/output --fasta '/projects1/Reference_Genomes/Human/hs37d5/hs37d5.fa' --bwaalnn 0.01 --fasta_index '/projects1/Reference_Genomes/Human/hs37d5/hs37d5.fa.fai' --bwa_index '/projects1/Reference_Genomes/Human/hs37d5/hs37d5.fa' --run_genotyping --genotyping_tool 'pileupcaller' --pileupcaller_bedfile '/projects1/Reference_Genomes/Human/hs37d5/SNPCapBEDs/1240K.pos.list_hs37d5.0based.bed' --pileupcaller_snpfile '/projects1/public_data/Datashare_Boston_Jena_June2018.backup/1240K.snp' --seq_dict '/projects1/Reference_Genomes/Human/hs37d5/hs37d5.dict' --email lamnidis@shh.mpg.de`

**Comment by jfy133** [comment]
Had sudden realisation so noting here for record: for the per individual issue, I think the issue was that the BED and SNP files weren't `.collect()`'ed , so weren't re-used.

**Comment by jfy133** [comment]
Done in https://github.com/nf-core/eager/pull/459
