### ISSUE TITLE
TSV template link should point to raw file format

### ISSUE THREAD

**Issue by TCLamnidis** [nf-core/eager#462]
> A template can be taken from [here](images/usage/nfcore-eager_tsv_template.tsv).

I've seen less Github-experienced users not realising that this link points to a non-empty file, because the table headers look like Github elements rather than part of the file. They then backtrack and copy the table from the docs directly into excel instead. This defeats the purpose of the template.

It would be more intuitive if the link either directly downloaded the linked file, or pointed to the raw format of the file. It will then be clear that one can copy/paste the headers and start filling in.

**Comment by jfy133** [comment]
Just had a thought: we could put it on testdata?

@apeltzer thoughts?

**Comment by jfy133** [comment]
Pleas see: https://github.com/nf-core/test-datasets/pull/165 , once merged will update link in docs.

**Comment by apeltzer** [comment]
You can have a go now ;-)
