### ISSUE TITLE
--tsv_input mentioned in usage.md isn't a valid option

### ISSUE THREAD

**Issue by ivelsko** [nf-core/eager#464]
I found the section on how to use an input tsv file to be unclear in 2 ways - 
1 - it doesn't say where/how to specify the tsv file in the input options: it's not clear if the path to the tsv file is given to `--input` instead of a path to fastq/bam files, or if it's given to `--tsv_input` as a separate option. If the second of those, does `--input` still need to be included, and what should be put there?
2 - it mentions several times `--tsv_input` but both links are broken, and this isn't a valid option when I tried to run it

Because I was uncertain about 1, I used 
`--tsv_input '/projects1/microbiome_calculus/iberian/02-scripts.backup/iberian_eager2.tsv'`
without including `--input`, but got an error 
`[nf-core/eager] error: --input was not supplied! Please see --help and documentation under 'running the pipeline' for details`.
When I ran `--input '/projects1/microbiome_calculus/iberian/02-scripts.backup/iberian_eager2.tsv'`, the pipeline started fine. 

It would be helpful to have this section specify that for `--input` you put either the path to fastq/bam files or the path to the tsv file. If `--tsv_input` isn't going to be used as an option, it would help to have it completely removed from the section

**Comment by jfy133** [comment]
Thank you for finding this. Indeed `--tsv_input` is incorrect and is a left over of a previous version. I will replace all these instances with `--input` (which is used for both types of input)

**Comment by jfy133** [comment]
Also feel free to make a PR with fixes wherever else you found the mistakes!
