### ISSUE TITLE
Should contamination estimation be ran per library instead of per individual?

### ISSUE THREAD

**Issue by TCLamnidis** [nf-core/eager#468]
If one library is contaminated (either in the lab, or because it is from a different sample of the same individual) and it is merged with another prior to contamination estimation, then the estimate could be lower than the cutoff value, even though contamination is added to the mix. 

If the contamination estimation is ran before merging libraries, then a user could more easily merge uncontaminated bams manually to exclude a contaminated library from the mix.

**Comment by jfy133** [comment]
Note to self: input channel for nuclear contamination process should come directly out of the two deduplication channels. This probably would also be relevent for PreSeq, and DamageProfiler (assuming you can get different levels of damage if you have differnet levels of contamination.)
