### ISSUE TITLE
FastA indexing + bwa indexing

### ISSUE THREAD

**Issue by apeltzer** [nf-core/eager#472]
Should follow more the examples of e.g .viralrecon: 

https://github.com/nf-core/viralrecon/blob/69326f97b1c1d1b8733a0df573cb1f3eff907e6d/main.nf#L163

and `ch_fasta = file(params.fasta)` 

And then use proper 

```
input:
    path fasta from ch_fasta
```

**Comment by jfy133** [comment]
Being addressed in https://github.com/nf-core/eager/issues/473

**Comment by jfy133** [comment]
> Should follow more the examples of e.g .viralrecon:
> 
> https://github.com/nf-core/viralrecon/blob/69326f97b1c1d1b8733a0df573cb1f3eff907e6d/main.nf#L163
> 
> and `ch_fasta = file(params.fasta)`
> 
> And then use proper
> 
> ```
> input:
>     path fasta from ch_fasta
> ```
