### ISSUE TITLE
Some more AWS issues

### ISSUE THREAD

**Issue by apeltzer** [nf-core/eager#473]
```
107[a3/57447f] Submitted process > endorSpy (JK2782)
108WARN: Directive 'validExitStatus' has been deprecated -- Check process 'nuclear_contamination'
109[94/330326] Submitted process > preseq (JK2782)
110Error executing process > 'sex_deterrmine'
111Caused by:
112  Can't stage file file:///NO_FILE -- file does not exist
113Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
```

**Comment by jfy133** [comment]
> Should follow more the examples of e.g .viralrecon:
> 
> https://github.com/nf-core/viralrecon/blob/69326f97b1c1d1b8733a0df573cb1f3eff907e6d/main.nf#L163
> 
> and `ch_fasta = file(params.fasta)`
> 
> And then use proper
> 
> ```
> input:
>     path fasta from ch_fasta
> ```

From the original issue report https://github.com/nf-core/eager/issues/472

**Comment by jfy133** [comment]
Had a successful run the other day. Running few last checks
