### ISSUE TITLE
Add output docs for all non-default modules. 

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#475]
Currently only default MultiQC modules are described, for both GeneralStats and sections.

Modules to be added:

- [x] bowtie2 [draft drawn]
- [x] malt <- [draft drawn] column required: % Metagenomic Mapped
- [x] kraken
- [x] picard markduplicates  [draft drawn] <- column required: duplication rate
- [x] mtnucratio <- only column name, number of 'mt' mapping reads for each non-mt mapping read 
- [x] sexdeterrmine [draft drawn] <- columns required: Rate X, Rate Y
- [x] multivcfanalyzer [draft drawn] <- columns required: % Hets

@ZandraFagernas I will send draft images when I've done them.
@TCLamnidis  can you please draft something for SexDet, and also a sketch for Zandra

**Comment by TCLamnidis** [comment]
- [ ] Nuclear contamination <- columns required #snps, estimate and error.
Currently working on it
