### ISSUE TITLE
ValidExitstatus should be deprecated in code

### ISSUE THREAD

**Issue by apeltzer** [nf-core/eager#478]
Use bash trap instead:

https://github.com/nextflow-io/nextflow/issues/1564
```
  trap 'if [[ $? == expected_error ]]; then echo OK; exit 0; fi' EXIT
```

**Comment by jfy133** [comment]
https://github.com/nf-core/eager/commit/4946b938f1e504db556c8edd72090d919a7e9263

Took the second version of `errorStrategy` instead!
