### ISSUE TITLE
Merging of ssDNA and dsDNA genotypes.

### ISSUE THREAD

**Issue by TCLamnidis** [nf-core/eager#481]
He Yu (a colleague) has developed a small tool to "smush" together genotypes from different libraries of the same individual. Some version of this could be implemented into eager to solve the issues with ssDNA vs dsDNA genotyping with pileupCaller. It would allow users to keep genotypes called with `--singleStrandMode` but also fill in any missing data that is genotyped in an accompanying dsDNA library of the same individual.

The (soon to be updated) implementation of pileupCaller will be creating two genotyping datasets, one for dsDNA and one for ssDNA libraries. Adding a genotype "smushing" option would allow us to provide a single dataset with a single version for each "duplicated"  individual that includes the best version of the data from both library types. 

The current implementation of He's tool randomly picks one of the genotypes in positions where both versions of an individual are genotyped. It might be good to add an option to overwrite this behaviour (so dsDNA/ssDNA is preferred if the user has a preference) before it is implemented in eager. 

I will look into `conda`ing and implementing the tool in eager after I discuss further with He.

**Comment by jfy133** [comment]
He's handle on here: @paulayu

**Comment by TCLamnidis** [comment]
Upon further discussion with the PopGen group in Jena, this idea was not very well received, at least for incorporation into eager.

The reason being that such a merging of genotypes becomes a bit too custom-made for eager. The user would need to really carefully think about what they are doing and what they will get out of this. It would be slightly unsafe to provide users with an "easy" way to hack these things together, which would also artificially increase the legitimacy of these genotypes.

Additionally, the preference of ss vs ds or vice versa would likely change depending on trimming, UDG treatment, and relative coverage of each library. 

I will therefore shelf this idea for now.
