### ISSUE TITLE
Add MetaPhlAn3 as further metagenomic alternative

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#487]
The MetaPhlAn series of taxonomic classifiers are very popular in metagenomics, and have very low overhead. It also allows exporting of physical alignments to the gene databases that theoretically (but see https://github.com/Integrative-Transcriptomics/DamageProfiler/issues/39) )could be sent to DamageProfiler for aDNA authentication criteria screening.

MetaPhLan: https://github.com/biobakery/MetaPhlAn/tree/3.0

**Comment by merszym** [comment]
Is already part of the dsl2-metagenomics branch
https://github.com/nf-core/eager/pull/1019
