### ISSUE TITLE
Update/remove old test configs

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#489]
We have pre-TSV era confs still avaliable. These should be updated (e.g. readPaths -> input) etc., or remove if we don't need them.

**Comment by apeltzer** [comment]
Remove

**Comment by jfy133** [comment]
I think I will keep one so we can check that running without TSV works. Will add to #502

**Comment by jfy133** [comment]
Added here https://github.com/nf-core/eager/pull/502/commits/1c8dc858dadc2ee45db41c80bf366b5edc7086a8
