### ISSUE TITLE
Increase the number of decimal points in multiQC reporting of Endogenous DNA.

### ISSUE THREAD

**Issue by TCLamnidis** [nf-core/eager#492]
We use a cutoff of 0.1% endogenous for capture. The current reporting of endogenous DNA with a single decimal makes rounding of the last digit untrustworthy for decision making in lower preservation samples (0.05 =/= 0.10).

**Comment by jfy133** [comment]
@aidaanva I think this is something we have to modify in the `pconfig` section of the JSON?

**Comment by TCLamnidis** [comment]
Also, add `"id": "endorSpy"` or similar to the JSON output, to avoid clashes with future custom content
