### ISSUE TITLE
Be explicit with input data (don't assume paired end and require flag when otherwise)

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#51]
**Is your feature request related to a problem? Please describe.**
I think it is 'dangerous' to assume paired end data, and require a `--singleend` switch when mapping with single end.

As sad as it is, I know quite a lot of clever people doing bioinformatics/downstream analysis but who rarely deal with raw sequencing data. When they do have to occasionally have to deal with it, they are often not familiar with sequencing configurations and may not understand why the pipeline is not working when submitting with single end data.  

It also doesn't make sense in the sense you are assuming what the most common type of data is, which is not the role of the pipeline (IMO)

**Describe the solution you'd like**

I think it would be beneficial _require_ a `--*end` flag, regardless of what you are submitting: i.e. you always require `--singleend` or `--pairedend`. Being explicit is a better presumed state for user-friendly pipelines that _anyone_ can run.

**Describe alternatives you've considered**
The pipeline itself could do an automatic detection based on the naming scheme (as you already require a specific naming scheme with R1/R2). This would also help if you have multiple lanes.

**Additional context**
None.

**Comment by apeltzer** [comment]
As there is no real "standard" sequencing protocol nowadays and most people have both paired end and single end, I think you make a valid point here! When I started in the field 90% were sequencing PE data, but that changed, so making it mandatory to state the kind of data you have is I think a good idea!
