### ISSUE TITLE
Allow for differential trimming based on UDG treatment?

### ISSUE THREAD

**Issue by TCLamnidis** [nf-core/eager#512]
We currently have a single trimming parameter for all libraries. This can become an issue if submitting half-UDG and non-UDG libraries together via TSV. The former need 2-3bp trimmed, but the latter can need 7-10 bp. So either you lose a bunch of data for no reason, or you retain damage in your data. 

We could branch the input by UDG treatment/SS/DS and have separate parameters for the end user to specify how much to trim in which libraries. 

Something like this
`--bamutils_clip_left` becomes `--bamutils_clip_left_halfudg` & `--bamutils_clip_left_nonudg`

Then the trimming process entails an if clause changing the specific parameters by library/udg type.

**Comment by jfy133** [comment]
Maybe a good idea - I don't think this would need to be branching even, just a condition in the script block.

Simple pseudocode:
i.e. `trim_amount = udg_treatment == 'half' ? params.clip_no_udg : params.clip_no_udg`

Don't know what the difference with SS would be though?

Thoughts @nf-core/eager ?
