### ISSUE TITLE
bedtools warning

### ISSUE THREAD

**Issue by yassineS** [nf-core/eager#516]
Bedtools occasionally issues a warning like this when using GRCh38: 

```

***** WARNING: File merged_bams/initial/A14937_libmerged_rg_rmdup.bam has inconsistent naming convention for record:
HLA-A*01:01:01:01	47	100	M_ST-E00180:295:H7JNVCCXY:7:2220:15229:45699	0	+
```

Bedtools continues running and produces a complete output. However, the error `137` results in the process being identified as "failed" by nextflow. It just requires an exception.

**Comment by jfy133** [comment]
Thanks for the report @yassineS !

Could you maybe run a manual test, and see if the following solution works?

https://github.com/arq5x/bedtools2/issues/628

If so I would prefer for that to work than 'ignoring' the error code, but in case it doesn't work, please can you test the fix on this branch: https://github.com/nf-core/eager/tree/bedtools-fix/

**Comment by yassineS** [comment]
Thanks, @jfy133 Just for the record, there are no mismatches between chromosome names in the bed file, the reference and the bam file. 

I tried the `-nonamecheck` option and it seems to have fixed the issue.

**Comment by jfy133** [comment]
Should be addressed inthe above!
