### ISSUE TITLE
Table layout in MultiQC

### ISSUE THREAD

**Issue by stschiff** [nf-core/eager#521]
I think MultiQC is awesome. But I'm struggling with the HTML Table layout a bit, specifically the very first on (called "General Statistics").

1.) I think it would be nice to have column widths resizable, or at least automatically size so that numbers are completely readable. If you show the table in default mode, 7-digit numbers are typically cut off.
2.) The column headings are a bit confusing, since they don't show the group. So in the default setup, for example, we see multiple columns named "Seqs" or "Length" in the beginning, without clear indication what those are. Only when you click on "Configure Columns" you also see the group, like pre- vs. post-AdapterRemoval.

**Comment by jfy133** [comment]
Ha, ok. Actually I was wrong, if it's just display - those things are all MultiQC specific!

https://github.com/ewels/MultiQC
