### ISSUE TITLE
Specify config requirements for running MALT in documentation

### ISSUE THREAD

**Issue by ashildv** [nf-core/eager#553]
I wanted to run only MALT / HOPS, however it was not clear from the documentation that I still need to supply a reference genome and that I needed to include some other parameters (eg. run_bam_filter= true)

It would be helpful if it was specifically specified that for MALT you must map and specify a decoy genome (e.g. phiX) It would be nice if the logic behind this was made clearer :)

Note from @jfy133: this should be added everywhere relevant

**Comment by jfy133** [comment]
Added in https://github.com/nf-core/eager/commit/69b7c80018aa0522bb78a8fa384c88207cd1e255 (will merge with other docs updates)

**Comment by ashildv** [comment]
Bar one comment that I made re: the 'skip_trim' option, it looks good as far as I can see
