### ISSUE TITLE
Adapter removal documentation

### ISSUE THREAD

**Issue by ashildv** [nf-core/eager#554]
Adapter removal2 documentation:
It would be helpful if the parameters choices for adapter removal, specifically for `trimns`, `trimqualities` and `trimwindows`, was made clearer in the documentation. It would be good if it was more explicitly specified that for `trimns` and `trimqualities` you can either run both or neither.

**Comment by jfy133** [comment]
Specified in https://github.com/nf-core/eager/commit/f7c2c8dac454e174ca3371dfa0fea89093355bc6

**Comment by ashildv** [comment]
Your changes look good to me :)
