### ISSUE TITLE
Specify the tool and tool specific parameter for all config parameters

### ISSUE THREAD

**Issue by ashildv** [nf-core/eager#555]
It would be very helpful if the tool and tool-specific parameter that each config parameter refers to was made clearer (it is already for some). For example, for `--bam_mapping_quality_threshold` it would be nice if it was specified that this is the `samtools view` `-q` parameter. This could be indicated next to the variable in parentheses or in the description, 
eg. `--bam_mapping_quality_threshold` (samtools view, -q)

**Comment by jfy133** [comment]
@ashildv this is added now. Is this format sufficient for you? e.g. https://github.com/nf-core/eager/pull/566/commits/87e64c0b829d2ce6662cf3e0153b0cf8c76dd1c6#diff-4be2078a125fe364f7198675d51bc688R988-R1018?
