### ISSUE TITLE
nextflow clean not finding anything to clean

### ISSUE THREAD

**Issue by ivelsko** [nf-core/eager#558]
I tried to clean my output folder after a run with MALT completed, but it doesn't find anything to clean. The `Clean up` section of usage.md says to run in the output folder, but the section `Tutorial Metagenomics - Clean up` says to run it one folder up from the results directory, however from both directories it found nothing to clean. Am I running the command in the wrong folder?

For the run I set:
--outdir `/projects1/microbiome_calculus/iberian/03-preprocessing/screening/eager2`
-work-dir `/projects1/microbiome_calculus/iberian/03-preprocessing/screening/eager2/work`

I started the run in a completely different folder 
`/projects1/microbiome_calculus/iberian/02-scripts.backup`

```
/projects1/microbiome_calculus/iberian/03-preprocessing/screening/eager2$ nextflow clean -n
It looks no pipeline was executed in this folder (or execution history is empty)
/projects1/microbiome_calculus/iberian/03-preprocessing/screening/eager2$ cd ..
/projects1/microbiome_calculus/iberian/03-preprocessing/screening$ nextflow clean -n
It looks no pipeline was executed in this folder (or execution history is empty)
```

**Comment by jfy133** [comment]
Sorry: `-profile shh` does that already for you!

Sorry :sweat_smile:
