### ISSUE TITLE
Cannot find output of "-metagenomic_tool kraken" 

### ISSUE THREAD

**Issue by macrobiotus** [nf-core/eager#576]
Dear Madam or Sir, 

Thank you for reading this. I have reviewed the contributing guidelines and code of conduct. I have recently started to use the Eager pipeline and it seems to be running for me. To avoid misunderstandings and to be verbose I have attached execution script in its entirety below this message, please excuse its length.

Despite the pipeline running through without errors (judging by report and Slurm email), I cannot seem to find the output of the call to Kraken after using ` --run_metagenomic_screening`  and  `--metagenomic_tool kraken`  Should those normally be in a dedicated results folder? The documentation at `https://github.com/nf-core/eager/blob/master/docs/usage.md` doesn't mention where the results could be found or how to gauge successful completion. Could this perhaps be added to the documentation?

Please accept my apologies if I am missing something. Thank you for your support.

Kind regards, 

Paul  

```
#!/usr/bin/env bash
#SBATCH -A uoo02328
#SBATCH -J slurmed_eager_kraken
#SBATCH --time 04:00:00
#SBATCH -N 1
#SBATCH -c 32
#SBATCH -n 1
#SBATCH --mem=190G
#SBATCH --mail-user=foo
#SBATCH --mail-type=ALL
#SBATCH --output 17th_run_eager.%j.out
#SBATCH --error 17th_run.%j.err

# 13.10.2020 - Paul Czechowski - foo
# ========================================================
# Run eager on cluster and locally
#   For Slurm options check
#     https://slurm.schedmd.com/sbatch.html
#   For Eager options at
#     https://github.com/nf-core/eager/blob/master/docs/usage.md#optional-reference-options

# safety settings 
#   "-u" makes it an error to reference a non-existent environment variable 
#   "pipefail" makes things like misspeled-command raise errors.

set -eu
set -o pipefail

# Adjust base paths
# -----------------
if [[ "$HOSTNAME" != "foo" ]] && [[ "$HOSTNAME" != "bar" ]]; then
    
    # adjust terminal and base directory
    bold=$(tput bold)
    normal=$(tput sgr0)

    # location message 
    printf "\n${bold}$(date):${normal} Execution on remote...\n"
    
    # prepare software computer 
    module purge
    module load Nextflow/19.10.0
    module load Singularity/3.5.2
    module load Kraken2/2.0.8-beta-gimkl-2018b
    module load BLAST/2.9.0-gimkl-2018b
    
    # set execution variables and paths
    # CPUSMAX="$(nproc --all)"
    CPUS=30
    
    # remote home is `/home/czepa05p/Documents`, scratch is `/nesi/project/uoo02328/paul`, local equivalent is `/Users/paul/Documents`
    BASPTH="/nesi/project/uoo02328/paul"
    NFCORE="/nesi/project/uoo02328/programs/Nextflow/nf-core-eager-2.1.0/"
    
    # path to raw data  
    READS[1]="${BASPTH}/OU_eagle_wgs/200907_analyses/raw_data/200831_OU_haast_eagle_run_01/OG6102-192920732/FASTQ_Generation_2020-08-28_16_46_04Z-304919615/6102-01-0-1_L001-ds.30ba3924733f460c8b1b94602f109226"
    READS[2]="${BASPTH}/OU_eagle_wgs/200907_analyses/raw_data/200831_OU_haast_eagle_run_01/OG6102-192920732/FASTQ_Generation_2020-08-28_16_46_04Z-304919615/6102-02-0-1_L001-ds.12af8aae24bb42c3b49d3dd022926985"
    
    # run names 
    NAME[1]="seventeenth_slurm_first_sample"
    NAME[2]="seventeenth_slurm_second_sample"
 
    # initial run - note: (when you use variables, you have to use double quotes, as in --reads and --fasta parameters below)
    for i in "${!READS[@]}"; do

      printf "\n${bold}$(date):${normal} Starting Eager run...\n" && \
      cd "${BASPTH}/OU_eagle_wgs/200907_analyses/adna_analyses/" && \
      pwd && \
        nextflow run "${NFCORE}/workflow/" \
          -profile singularity \
          -with-singularity "${NFCORE}/singularity-images/nf-core-eager-2.1.0.simg" \
          --paired_end \
          --reads "${READS[$i]}/*R{1,2}*.fastq.gz" \
          --fasta "${BASPTH}/OU_eagle_wgs/200907_analyses/reference_genomes/Hieraaetus_morphnoides_assembly_gapcloser.fa.gz" \
          --outdir "${BASPTH}/OU_eagle_wgs/200907_analyses/adna_analyses/${NAME[$i]}" \
          --max_memory '180.GB' \
          --max_cpus "$CPUS" \
          -name "${NAME[$i]}" \
          --bam_discard_unmapped \
          --bam_unmapped_type 'fastq' \
          --run_metagenomic_screening \
          --metagenomic_tool kraken \
          --database "/opt/nesi/db/Kraken2/nt" \
          --max_time '2.h' && \
        printf "${bold}$(date):${normal}...finished Eager run.\n"
      
      done 
      
      # cleanup temp files
      cd "${BASPTH}/OU_eagle_wgs/200907_analyses/adna_analyses/" && nextflow clean -f -k

elif [[ "$HOSTNAME" == "foo" ]]  || [[ "$HOSTNAME" == "bar" ]]; then
    
    # adjust terminal and base directory
    bold=$(tput bold)
    normal=$(tput sgr0)

    # location message 
    printf "${bold}$(date):${normal} Execution on local is not set up and not purposeful...\n"

fi
```

**Comment by jfy133** [comment]
Thanks for the message! I'm currently on the move the whole day so can't look closely until the evening, - but can you check in the log Kraken was actually executed, and if it was, the results should be under `results/metagenomic_classifictiom` (or similar)

**Comment by macrobiotus** [comment]
Thank you for your reply. I will check back in the morning myself, it is night where I am. I am afraid this output directory you may be expecting is not created  or I can't see it. My results folders look as in attached screenshot. Kind regards, Paul

<img width="188" alt="Screen Shot 2020-10-14 at 23 37 38" src="https://user-images.githubusercontent.com/10920135/95978515-c640d700-0e76-11eb-8d42-8a456ad5d445.png">

**Comment by apeltzer** [comment]
@jfy133 might be a bug too - @macrobiotus you are using version 2.1.0 of the pipeline, correct?

**Comment by macrobiotus** [comment]
> @jfy133 might be a bug too - @macrobiotus you are using version 2.1.0 of the pipeline, correct?

Hello, thank you for your support, yes I am using version 2.1.0, also see the screenshot attached here.
![Screen Shot 2020-10-15 at 12 26 11](https://user-images.githubusercontent.com/10920135/96055951-e8237380-0ee1-11eb-88bd-35f8c44bf9bf.png)

**Comment by jfy133** [comment]
Hi @macrobiotus,

I just tried replicating your issue, and identified the problem: you did not specify to turn on the bam filtering module with `--run_bam_filtering \`. So while you specified the options for that module (i.e. to extract the unmapped reads), that module wasn't executed itself and therefore kraken did not run.

We are already aware this was a bit confusing, and the way to perform the unmapped read extraction has been rejigged in `-r dev` (likely being release this week or next week as `-r 2.2`), so hopefully this will be more intuitive! Sorry about that.

I will leave this issue open until you can report back that you do indeed get the `metagenomic_classification/` output :), if you do feel free to close.

As a side note: is there any reason why you are running the command in a for-loop? If I understand the loop separately, you are running nf-core/eager separately on each pair of FastQ files separately - however this shouldn't be necessary as nf-core/eager does this for you:

i.e. `--reads "${BASPTH}/OU_eagle_wgs/200907_analyses/raw_data/200831_OU_haast_eagle_run_01/OG6102-192920732/FASTQ_Generation_2020-08-28_16_46_04Z-304919615/*/*R{1,2}*.fastq.gz`

and then all your results will be in a single report.

Apologies if that is a bit presumptious because of course you may have a valid reason, but I just want to make sure you know, as running everything together makes the whole procedure overall more efficient.

**Comment by macrobiotus** [comment]
James,

Thank you for following up I really appreciate it. Will close the issue as soon as I have my results back. The loop indeed was on purpose now, but your recommendation will come in handy soon.

Cheers,

Paul

**Comment by macrobiotus** [comment]
Looking good now - see attached screenshot. Thanks again.
![Screen Shot 2020-10-16 at 17 17 12](https://user-images.githubusercontent.com/10920135/96212535-a4109b80-0fd3-11eb-8baf-656612ea0ed5.png)
