### ISSUE TITLE
Documentation for qualimap doesn't account for large genomes 

### ISSUE THREAD

**Issue by TCLamnidis** [nf-core/eager#578]
https://github.com/nf-core/eager/blob/dev/docs/output.md#qualimap

The expected coverage histograms and cumulative coverage histograms for larger genomes (e.g. human) would include a majority of 0x coverage positions, with some positions having 1x and fewer having 2x etc. (See reference image below) 

This will be the case for the majority of human aDNA data, since we can rarely produce 30x whole genome sequencing data. The docs should be updated to mention/acknowledge this possibility. 

<img width="1109" alt="Screenshot 2020-10-16 at 15 59 40" src="https://user-images.githubusercontent.com/22079185/96270655-3ca31d80-0fcc-11eb-8566-1b2c5f2f531c.png">
The above is results from human aDNA.

**Comment by jfy133** [comment]
- [ ]
