### ISSUE TITLE
Adding AuthentiCT to the pipeline?

### ISSUE THREAD

**Issue by TCLamnidis** [nf-core/eager#597]
[AuthentiCT](https://github.com/StephanePeyregne/AuthentiCT) uses ancient DNA damage on non-UDG treated ssDNA libraries to provide nuclear contamination rates. After a presentation by @StephanePeyregne of the method in the Jena popgen meeting (29/10/2020) it seems like it could have interesting applications as a contamination estimate for this type of libraries, especially since it should already be applicable from initial shotgun screening. 

Compared to existing methods (like ANGSD etc) AuthentiCT does not make any assumptions on ancestry, and instead uses only the damage information. However, by default it returns per-sequence contamination rate, rather than per-base contamination rate, which slightly complicates the reporting of these estimates side-by-side with other estimates (since the two are not exactly comparable in their vanilla form).

As a side usage, AuthentiCT can also separate damaged and non-damaged reads similarly to PMDtools. 

The use commands seemed straight forward, so implementation within eager could be a possibility in the (near) future, which I would volunteer to do. I am making this issue as a placeholder/reminder for now, as there is some testing to be done first before implementation is attempted.

I will also tag here @stschiff for future discussions.

**Comment by jfy133** [comment]
Please use the search bar in the future :-*https://github.com/nf-core/eager/issues/371
