### ISSUE TITLE
endorSpy results not being displayed in MultiQC Config

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#608]
However JSONs are present in `results/`. I suspect this is something to do with conflicting custom_content, but I don't see anything in the MultiQC log. I also vaguely remember seeing this before when people ran print_human_contamination -  will need to investigate further.

Reported by @scarlhoff

**Comment by scarlhoff** [comment]
Just wanted to say that this has been fine with my recent runs using the "correct" parameters, so it might just be certain parameters overlapping somehow.

**Comment by jfy133** [comment]
Hmm ok, that's good to know.

If you happen to have (no problem if not) the command where it wasn't displayed that would be helpful for me to try and replicate it.

**Comment by scarlhoff** [comment]
Lucky you! 
So for the following parameters it didn't work (in brackets are parameters added in unsuccessful attempt no 2):

```
params {
config_profile_description = "human shotgun data hg19"
config_profile_contact = "Selina Carlhoff (@scarlhoff)"
fasta = "/projects1/Reference_Genomes/Human/HG19/hg19_complete.fasta"
fasta_index = "/projects1/Reference_Genomes/Human/HG19/hg19_complete.fasta.fai"
bwa_index = "/projects1/Reference_Genomes/Human/HG19/"
seq_dict = "/projects1/Reference_Genomes/Human/HG19/hg19_complete.dict"
skip_preseq = true
complexity_filter_poly_g = true
(clip_readlength = 0)
(preserve5p = true)
(mergedonly = true)
bwaalnn = 0.01
bwaalnl = 16500
run_bam_filtering = true
bam_mapping_quality_threshold = 30
(bam_filter_minreadlength = 20)
bam_unmapped_type = "discard"
dedupper = "dedup"
dedup_all_merged = true
run_mtnucratio = true
mtnucratio_header = "chrMT"
run_sexdeterrmine = true
(sexdeterrmine_bedfile = "/projects1/Reference_Genomes/Human/HG19/SNPCapBEDs/1240K.pos.list_hg19.0based.bed")
run_nuclear_contamination = true
contamination_chrom_name = "chrX"
}
```

But for these the Endogenous DNA % column was displayed (aka switching to markduplicates for SE data):
```
params {
config_profile_description = "human shotgun data hg19 SE"
config_profile_contact = "Selina Carlhoff (@scarlhoff)"
fasta = "/projects1/Reference_Genomes/Human/HG19/hg19_complete.fasta"
fasta_index = "/projects1/Reference_Genomes/Human/HG19/hg19_complete.fasta.fai"
bwa_index = "/projects1/Reference_Genomes/Human/HG19/"
seq_dict = "/projects1/Reference_Genomes/Human/HG19/hg19_complete.dict"
skip_preseq = true
clip_readlength = 0
preserve5p = true
bwaalnn = 0.01
bwaalnl = 16500
run_bam_filtering = true
bam_mapping_quality_threshold = 30
bam_filter_minreadlength = 25
bam_unmapped_type = "discard"
run_mtnucratio = true
mtnucratio_header = "chrMT"
run_sexdeterrmine = true
sexdeterrmine_bedfile = "/projects1/Reference_Genomes/Human/HG19/SNPCapBEDs/1240K.pos.list_hg19.0based.bed"
run_nuclear_contamination = true
contamination_chrom_name = "chrX"
}
```

**Comment by jfy133** [comment]
Thank you very much!

But unfortunately this now makes less sense to me :laughing:  the only things that _should_ conflict are endorS.py and run_nuclear_contamination I believe. But it looks like they were both ran in both cases. So if in one case %endo was displayed and in one not, that suggests some wierd instability in MultiQC for whatever reason :thinking: . 

I will if I can replicate it first, if not, we will close and re-open it if more people report more issis.

**Comment by jfy133** [comment]
I've not been able to replicate for the time being. Will close for now, but re-open if it crops up again.
