### ISSUE TITLE
Pipeline crashes when supplying bwa_index with circular mapper

### ISSUE THREAD

**Issue by scarlhoff** [nf-core/eager#610]
Hi! 
As the name suggests, my eager2 session was aborted when I supplied bwa_index despite using circular mapper for mitochondrial capture data. 

`Nov-13 14:09:00.144 [main] DEBUG nextflow.Session - Session aborted -- Cause: Unknown variable 'bwa_index'`

Here is the command 
`nextflow run nf-core/eager -r 2.2.1 -c ~/eager2.config -profile humanMT,sdag,shh --input MTcap.tsv`

and profile I was using:
`profiles {
	humanMT {
		params {
			config_profile_description = "human MT data HG19 SE"
			config_profile_contact = "Selina Carlhoff (@scarlhoff)"
			fasta = "/projects1/Reference_Genomes/Human/HG19/hg19_MT.fasta"
			fasta_index = "/projects1/Reference_Genomes/Human/HG19/hg19_MT.fasta.fai"
			bwa_index = "/projects1/Reference_Genomes/Human/HG19/"
			seq_dict = "/projects1/Reference_Genomes/Human/HG19/hg19_MT.dict"
			skip_preseq = true
			clip_readlength = 0
			preserve5p = true
			mapper = "circularmapper"
			circulartarget = "NC_012920.1"
			run_bam_filtering = true
			bam_mapping_quality_threshold = 30
			bam_filter_minreadlength = 25
			bam_unmapped_type = "discard"
		}
	}
}`
Thanks!

**Comment by jfy133** [comment]
I think due to: https://github.com/nf-core/eager/blob/7971d89e54621c44055b2062a569c76a36045723/main.nf#L331
