### ISSUE TITLE
Combining the genotypes from single- and double-stranded samples

### ISSUE THREAD

**Issue by scarlhoff** [nf-core/eager#614]
Me again 😁 

I already really appreciate that genotyping with pileupCaller as implemented in eager2 works for both single- and double-stranded libraries in the same run, creating two genotypes. The icing on the cake would be an integrated combination of these two genotypes to result in just one genotype output, provided the libraries all come from different samples. 

Thank you!

PS. For people not familiar with pileupCaller yet, adding a sentence to the pileupCaller section of the eager2 docs about how it exactly deals with single-stranded libraries without requiring trimming would probably convince them to switch 😉

**Comment by jfy133** [comment]
@TCLamnidis two for you <3

**Comment by TCLamnidis** [comment]
Addressed in #1016
