### ISSUE TITLE
Typo documentation v2.2.1

### ISSUE THREAD

**Issue by ashildv** [nf-core/eager#623]
In the documentation for v 2.2.1 there is a word missing in the sentence:
"After mapping, and prior BAM filtering, BAM files with the same **[term missing here]** with different SeqType (but with all other metadata columns the same) will be merged together for each Library."

**Comment by ashildv** [comment]
Another typo:
'actual' should be 'actually'
"You should provide a small decoy reference genome with pre-made indices, e.g. the human mtDNA or phiX genome, for the mandatory parameter --fasta in order to avoid long computational time for generating the index files of the reference genome, even if you do not **actual** need a reference genome for any downstream analyses."

**Comment by 96RadhikaJadhav** [comment]
@ashildv  Could you please assign this issue to me? I wish to work on it.

**Comment by ashildv** [comment]
Hi, I am not able to assign someone, I don't have permissions to do so. 
@jfy133 can you give me permissions, or assign @96RadhikaJadhav? :)

**Comment by jfy133** [comment]
Done!

@apeltzer could you add Ash to the nf-core organsation so she cna have assigning powers? ;)

**Comment by apeltzer** [comment]
@ashildv just invited you to nf-core and made you a member of team eager ;-) 

=> please also consider joining with your institution for the homepage - how to do this can be found here: https://github.com/nf-core/nf-co.re/issues/552#issuecomment-738244625

**Comment by 96RadhikaJadhav** [comment]
@apeltzer @jfy133 I have created a PR. Could you please review it?

**Comment by jfy133** [comment]
Fixed in the 'cleanup PR'/Template merge with  https://github.com/nf-core/eager/pull/625/commits/21e6e8cb315abf66c46e3ceb793ac11a205b17d6

**Comment by jfy133** [comment]
https://github.com/nf-core/eager/pull/625
