### ISSUE TITLE
tsv empty column error

### ISSUE THREAD

**Issue by scarlhoff** [nf-core/eager#626]
Hello! 

Forgetting to put NA (or anything) in the BAM column of the tsv file currently results in this unspecific error:

`Cannot invoke method matches() on null object
 -- Check script '/projects1/clusterhomes/carlhoff/.nextflow/assets/nf-core/eager/main.nf' at line: 3424 or see '.nextflow.log' file for more details`

row 3424 contains: `def bam = row.BAM.matches('NA') ? 'NA' : return_file(row.BAM)`

Would be great if the error could be more specific, since it looks more scary than it is.

**Comment by jfy133** [comment]
I guess 'nothing' isn't considered a string by `matches` so fails (rather than continue to the downstream file validation step). 

Should throw an error if it's nothing.
