### ISSUE TITLE
samtools version

### ISSUE THREAD

**Issue by barlavi1** [nf-core/eager#633]
## Is your feature request related to a problem? Please describe

The current samtools version isn't working on my data (for indexing)

## Describe the solution you'd like

A way to specify the version of samtools I'd like to use 

## Describe alternatives you've considered

a way to specify a path to a locally installed samtools

## Additional context

As newer versions of samtools cannot cope with large data, I need a way to incorporate samtools0.1.19 in the pipeline in order for it to work

thanks!
bar

**Comment by jfy133** [comment]
Hi @barlavi1 

This seems like a bug not an enhancement. We already have support for large genome indexing with the `.csi` suffix with `--large_ref`.

Also I think you maybe mistaken, Samtools version 0.1.19 is from 2013 (https://sourceforge.net/projects/samtools/files/samtools/0.1.19/)?

I will close this, but please re-open a new issue but with a bug report (and all the additional information we need for this).

**Comment by jfy133** [comment]
more clairifcation: the parmaeteR: https://nf-co.re/eager/2.2.2/parameters#large_ref

you must be running eager versoin >2.2.0 for this.
