### ISSUE TITLE
Allow multiple sets of adapters to be supplied

### ISSUE THREAD

**Issue by ashildv** [nf-core/eager#651]
Hi there,
I wonder if it would be possible to add a feature in the pipeline allowing libraries made with different adapter sequences to be processed in the same run.

For example, my colleagues and I are often working with a mixture of Illumina and BGI (4 channel) sequencing data and it would be cool to be able run these data together, instead of having to run adapter removal separately for each dataset before combining them in a single run.

**Comment by apeltzer** [comment]
Sounds good to me - I fear we might have to check how easy to implement this is but should be possible.

**Comment by jfy133** [comment]
Adapter removal already does this, planning to do something similar for the barcodes. So should be feasible I believe!

**Comment by jfy133** [comment]
Or not even that! Even simpler! https://adapterremoval.readthedocs.io/en/latest/examples.html#trimming-paired-end-reads-with-multiple-adapter-pairs

**Comment by jfy133** [comment]
@ashildv could you please manually try running Adapter removal with the instructions in the link above, where you have all your different adapters in the file, to see if it works?

I.e. adapter list of all bgi/illumina adapters. Then run with the adapter list against the bgi and illumina data respectively and see if it works?

If this works please let me know and can add adapter list as an option

**Comment by ashildv** [comment]
Will do!

**Comment by apeltzer** [comment]
Perfect, sounds like the right thing to do if this works as expected 👍🏼
