### ISSUE TITLE
File name collision when including single stranded and double stranded of same sample

### ISSUE THREAD

**Issue by aidaanva** [nf-core/eager#653]
## Check Documentation

I have checked the following places for your error:

- [x] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [x] [nf-core/eager pipeline documentation](https://nf-co.re/nf-core/eager/usage)
      - nf-core/eager FAQ/troubleshooting can be found [here](https://nf-co.re/eager/usage#troubleshooting-and-faqs)

## Description of the bug

When running single stranded and double stranded libraries of the same sample, it complains about duplicated names after the merging step.

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: `nextflow run nf-core/eager -profile pathogen_loose,sdag,shh -r 2.2.2 --fasta '/path/to/file.fasta' --input '/path/to/file.tsv ' --outdir '/path/to/directory' -w '/path/to/directory/work' --email 'blabla@blabla.de' -with-tower -name 'Nameofrun' --preserve5p --run_bam_filtering --bam_unmapped_type 'discard' --bam_mapping_quality_threshold 37 --dedupper 'markduplicates'`
2. See error: 
`Error executing process > 'sex_deterrmine (1)'

Caused by:
  Process `sex_deterrmine` input file name collision -- There are multiple input files for each of the following file names: ARS007_libmerged_rg_rmdup.bam

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
`

## Expected behaviour

Single and double stranded libraries are named automatically and they do not merge. 

## Log files

Have you provided the following extra information/files:

- [ ] The command used to run the pipeline
- [ ] The `.nextflow.log` file 
- [ ] The exact error: 

## System

- Hardware: 
- Executor: 
- OS: 
- Version 

## Nextflow Installation

- Version: 

## Container engine

- Engine: 
- version: 
- Image tag: 

## Additional context

I have spoken to @jfy133 privately

**Comment by jfy133** [comment]
Simplest solutuion is to append `_ss` and `_ds` to each BAM file. After discussion with a few people genotyping should still be performed on SS and DS libs separately as differences are fully explored yet it appears. 

Only downside is Sex. Det. will be performed on each separately rather than combined. If it's really important @TCLamnidis is welcome to add an additional library merge once I've added the `_ss` and `_ds` IDs
