### ISSUE TITLE
Print nuclear contamination fails (input files not staged)

### ISSUE THREAD

**Issue by IdoBar** [nf-core/eager#666]
## Check Documentation

I have checked the following places for your error:

- [x] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [x] [nf-core/eager pipeline documentation](https://nf-co.re/nf-core/eager/usage)
      - nf-core/eager FAQ/troubleshooting can be found [here](https://nf-co.re/eager/usage#troubleshooting-and-faqs)

## Description of the bug

Print nuclear contamination process fails because input files not staged properly (or their folder not bound to `singularity`) and are not available for  `print_x_contamination.py`

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: `nextflow run nf-core/eager -r 2.3.1 -params-file $BATCH.$REF.$ALIGNER.$GENOTYPER.json -c $HOME/.nextflow/qris.config --run_nuclear_contamination true`
2. See error below

## Expected behaviour

Process `print_nuclear_contamination` should complete successfully.

## Log files

Have you provided the following extra information/files:

- [x] The command used to run the pipeline
- [x] The `.nextflow.log` file 

- [x] The exact error: 
```
Error executing process > 'print_nuclear_contamination'

Caused by:
  Process `print_nuclear_contamination` terminated with an error exit status (1)

Command executed:

  print_x_contamination.py /gpfs1/scratch/30days/ibar/data/Human/WWR/WWR_NF1_process_14_01_2021/work/66/55a91e9b518c14871a04bde5f4c3ea/UWW1_T.X.contamination.out /gpfs1/scratch/30days/ibar/data/Human/WWR/WWR_NF1_process_14_01_2021/work/65/b35ed87179673efedd082c3e5253b5/UWW1_BP.X.contamination.out /gpfs1/scratch/30days/ibar/data/Human/WWR/WWR_NF1_process_14_01_2021/work/78/de48ec85aa16c1b8b26ff23d203cd5/UWW1_B.X.contamination.out

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/home/ibar/.nextflow/assets/nf-core/eager/bin/print_x_contamination.py", line 40, in <module>
      with open(fn, 'r') as f:
  FileNotFoundError: [Errno 2] No such file or directory: '/gpfs1/scratch/30days/ibar/data/Human/WWR/WWR_NF1_process_14_01_2021/work/66/55a91e9b518c14871a04bde5f4c3ea/UWW1_T.X.contamination.out'

Work dir:
  /gpfs1/scratch/30days/ibar/data/Human/WWR/WWR_NF1_process_14_01_2021/work/ee/8e69d3c9294f243ad37369370b0c27

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out
```

## System

- Hardware: HPC
- Executor: PBSPro
- OS: RHEL
- Version Linux 3.10.0-693.5.2.el7.x86_64
- Runtime: Groovy 3.0.5 on OpenJDK 64-Bit Server VM 11.0.1+13-LTS

## Nextflow Installation

- Version: 20.10.0 build 5430

## Container engine

- Engine: Singularity
- version: 3.6.3
- Image tag: nfcore/eager:2.3.1

## Additional context

I'm not exactly sure how `nextflow` stages input files, but my guess is that because the input files for the `print_nuclear_contamination` process is provided with `val 'Contam' from ch_from_nuclear_contamination.map { it[7] }.collect()` instead of as `path`, then the files were not staged properly, see below the content of the `stage` process in `.command.run`:
```
nxf_stage() {
    true
}
```
I could get the command to run successfully when I bind the work folders of each sample's `nuclear_contamination` run to singularity with `-B` flag.

**Comment by apeltzer** [comment]
That does sound a bit odd tbh, pinging  @TCLamnidis on that one as he's the expert on the contamination step.

**Comment by IdoBar** [comment]
@apeltzer, I believe that this is a `nextflow` scripting issue than the actual nuclear contamination command itself.

**Comment by jfy133** [comment]
@IdoBar 's comments in slack could indeed be relevant. Could either be an issue with angsd not making any output, or that the processes using a `val` to specify input stuff (this has been a problem in the past too).

**Comment by IdoBar** [comment]
I just tested it and it's an easy fix, just replace the `val` with `path` and it works.

**Comment by jfy133** [comment]
Ok that's promising, but need to verify with @TCLamnidis iirc there was a problem with that originally...
