### ISSUE TITLE
Docs are broken

### ISSUE THREAD

**Issue by apeltzer** [nf-core/eager#674]
Just checked the docs but found that these are not rendered on the nf-co.re webpage unfortunately... not sure whats going on there 🤔 

![image](https://user-images.githubusercontent.com/2359510/106738825-b5c88e00-6618-11eb-9660-7e51a7fb7700.png)

**Comment by jfy133** [comment]
Works for me?

![image](https://user-images.githubusercontent.com/17950287/106744691-61291100-6620-11eb-892a-b1e3c8c63ce4.png)

What version is that?

**Comment by apeltzer** [comment]
2.3.1, but this looks more like my broken proxy settings. Sorry for that
