### ISSUE TITLE
Large scale Multiqc breaks

### ISSUE THREAD

**Issue by apeltzer** [nf-core/eager#681]
Originally reported by Alexandre Gilardet, it seems to be problematic when creating thousands of symlinks on some filesystems when running the pipeline on large sample sizes. 

Thus, we should consider moving the MultiQC Process to:

- more memory
- more cpus?

AND

use `stageinmode : 'copy'` for the multiqc process. https://www.nextflow.io/docs/latest/process.html#stageinmode

**Comment by jfy133** [comment]
I think we should close this until this is reported again, as it's not easily reproducibile atm.
