### ISSUE TITLE
Please support longer insert sizes in paired-end data.

### ISSUE THREAD

**Issue by charles-plessy** [nf-core/eager#729]
## Is your feature request related to a problem? Please describe

My insert size is distributed between 100 and 1000 nt.  However, `bowtie2`'s default size for maximum insert size (`--maxins` parameter) is 500…

## Describe the solution you'd like

Could you either pass a max insert size of ~1000 to aligners, or provide an option to override the default ?

## Describe alternatives you've considered

I could not find an alternative way of doing this with _nf-core/eager_.

## Additional context

I am using _nf-core/eager_ as simple realignment and QC pipeline for non-ancient DNA, because 1) there is no alternative in _nf-core_ and b) _eager_ is very good for that purpose.  Thank you for developing it !

**Comment by jfy133** [comment]
Yup - should be easiy to add! It will take a little bit of time as the main developers are both swamped with other work, but should get to this in about a week!

**Comment by jfy133** [comment]
Unless you feel like making a PR of course ;)
