### ISSUE TITLE
No description of 'default' pipeline steps

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#78]
**Describe the bug**
Currently it is possible to run the pipeline with basic mandatory options (reads input, reference, profile), but what happens when you run this doesn't seem to be currently described anywhere.

While a user could look through the output results, it would be good to specify this is actually possible and what is actually going on. This will make clearer to novice users that one _can_ customise the pipeline parameters itself, and should not necessarily rely on defaults.

**Request**

Could @apeltzer please describe somewhere these steps, and I can include this in the documentation somewhere.

**Comment by apeltzer** [comment]
Current setting is this:

- run FastQC on input
- create reference indices (if didn't specify bwa_index etc pp) 
- adapter clipping / merging
- map with bwa aln, convert to BAM, apply no filtering of reads
- basic sam statistics with samtools idxstats
- damageprofiler
- qualimap bamqc for stats
- deduplication with dedup 
- preseq on dedup histogram
- multiqc reporting

Steps that are only turned on when users really specify this:

- bamclipping (for udg+/udg + 0.5 protocols)
- circularmapper
- bwa mem

I'll get this updated :-)
