### ISSUE TITLE
Handle reference genomes properly

### ISSUE THREAD

**Issue by apeltzer** [nf-core/eager#79]
Currently setting `-bwa_index` doesn't do anything. We should read in files from the selected path and push these to the same input channel that the indexing process uses as well ...

**Comment by jfy133** [comment]
I am also wondering if you should just _require_ providing the index file as a mandatory option. I know from EAGER v1 I always had problems (initially) when submitting parallel runs runs, that each run trying to index the same file was a mess and lead to lots of crashes.

As it is something you technically only need to do once anyway, I think it makes sense to expect it to be provided by the user. One of the principle of the EAGER pipeline is to be applying different data to the same set of tools (which the sequence doesn't change - just minor options). One could argue a reference is the the same, as you are generally applying mapping samples to the same reference.

**Comment by apeltzer** [comment]
I think we're going to have three options:

a.) Using FastA, which will create the indices on-the-fly as in EAGER v1, but with the addition that Nextflow can handle this kind of behaviour instead of starting to index files multiple times simultaneously, causing errors (thanks to nextflow, this is working very well and I couldn't get it to crash when testing)

b.) Using the `--bam_index`... etc options, then using the previously created Bam indices.

c.) Using iGenomes as a resource, then being able to download the reference genomes on the fly automatically, including indices as well. 

I totally see your point as this should just be done once per reference genome anyways and could thus be simply specified by users in general... so input on these three points is appreciated :-)

**Comment by apeltzer** [comment]
Fixed in #80 

iGenomes will be part of a future addition .-)
