### ISSUE TITLE
Chunking and stitching to parallelise alignment

### ISSUE THREAD

**Issue by pontussk** [nf-core/eager#797]
It would be very useful to have automated splitting of large fastq files to parallelise alignment, and then have automated concatenation of the output aligned files. BWA alignment is often the most time-consuming step of processing.

This could speed up processing of e.g. mammalian ancient genome sequencing which can be 300-4000 million reads from a single library.

**Comment by jfy133** [comment]
This would be good for a centralised nf-core module. One for the upcoming hackathon!

**Comment by jfy133** [comment]
This is already done with `sharding` from @shyama-mama !

https://github.com/nf-core/eager/pull/1023
