### ISSUE TITLE
Add leeHom as alternative trimming/merging

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#799]
It's now on bioconda, and seems that it will be more often used at EVA

**Comment by jfy133** [comment]
Need to make MQC

**Comment by apeltzer** [comment]
Leehom is on multiqc already - Gabriel added it 👍

**Comment by jfy133** [comment]
Noooooooooooooooooooooice

**Comment by jfy133** [comment]
It appears actually leeHom  will be deprecated in favour of AdapterRemoval or Fastp at EVA so we can skip this
