### ISSUE TITLE
CircularMapper should be a subworkflow

### ISSUE THREAD

**Issue by apeltzer** [nf-core/eager#801]
Just to note things down while they are fresh:

The CircularMapper step should actually be a subworkflow in the DSL2 version, as it encompasses multiple steps that have already existing modules (e.g. BWA Index, ALN, Samse/SAMPE, realignsamfile <-- module writing, samtools sort, samtools index)

Instead of the generator it should be:

CM_GENERATOR, BWA INDEX

Instead of having one step "mapper" it should be: 

BWA_ALN, BWA_SAMSE/BWA_SAMPE, CM_REALIGNSAMFILE, SAMTOOLS_SORT, SAMTOOLS_INDEX

**Comment by jfy133** [comment]
Done in https://github.com/nf-core/eager/blob/dev/subworkflows/local/circularmapper.nf
