### ISSUE TITLE
Allow input samplesheets to have additional metadata columns

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#821]
For many projects having a 'common' sheet that is reused across all analyses and contains all relevant metadata for all libraries/samples is useful to have.

It would be nice if we our input TSV samplesheet check can accept when the input TSV has additional columns (even if we don't use them)

**Comment by apeltzer** [comment]
Should be fair to ignore additional columns and just look for the ones we really rely on / need 💯

**Comment by jfy133** [comment]
@TCLamnidis do you think it would be possible based on what we've done so far?

**Comment by maxulysse** [comment]
We're doing that in sarek

**Comment by scarlhoff** [comment]
This is possible with samplesheet validation by nf-validation as implemented in #710. I will close this issue
