### ISSUE TITLE
Message for metagenomic screening not clear

### ISSUE THREAD

**Issue by aidaanva** [nf-core/eager#828]
## Check Documentation

I have checked the following places for your error:

- [x] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [x] [nf-core/eager pipeline documentation](https://nf-co.re/nf-core/eager/usage)
      - nf-core/eager FAQ/troubleshooting can be found [here](https://nf-co.re/eager/usage#troubleshooting-and-faqs)

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: `nextflow run nf-core/eager -c /bla/bla/screening_.config -profile eva,archgen,big_data,hops_phiX -r 2.4.2 --input /bla/bla/input.tsv --outdir /bla/bla/output --run_metagenomic_screening` + all other parameters for metagenomics screening
2. See error: _Please provide your error message_
`[nf-core/eager] error: metagenomic classification can only run on unmapped reads. Please supply --bam_unmapped_type 'fastq'. Supplied: --bam_unmapped_type 'discard'.`

## Expected behaviour

When --run_metagenomic_screening is given however no bam filtering has been turn on, the message is unclear and it only mentions to set up the --bam_unmapped_type to 'fastq'. It should also remind you to turn on --run_bam_filtering
## Log files

Have you provided the following extra information/files:

- [x] The command used to run the pipeline
- [ ] The `.nextflow.log` file 
- [x] The exact error: 

## System

- Hardware: 
- Executor: 
- OS: 
- Version 

## Nextflow Installation

- Version: 

## Container engine

- Engine: 
- version: 
- Image tag:

**Comment by jfy133** [comment]
If we need to do another patch release for a major bug, I'll throw this in. Otherwise we will make sure that this is fixed in our DSL2 conversion
