### ISSUE TITLE
Update sequenceTools

### ISSUE THREAD

**Issue by stschiff** [nf-core/eager#829]
Hi team,

I've updated the sequenceTools package on bioconda a while ago to version 1.5.1, which among other improvements now has Plink output support. Please update the version shipped with the nf-core/eager pipeline. 

Thank you!

**Comment by TCLamnidis** [comment]
v1.5.2 just released with a bugfix that is important when users use a Reference file that includes lowercase (soft-masked) positions, like the one provided by UCSC.

https://github.com/stschiff/sequenceTools/releases/tag/v1.5.2
