### ISSUE TITLE
Not able to generate picard dict file

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#83]
**Describe the bug**
When running the pipeline using `-profile shh,singularity`, the pipeline crashes at `picard CreateSequenceDictionary` with a 127 error. Singularity reports 'no such file or dictionary'. 

From the 'Command executed' message - I think this is because this step does not take into account the path to the reference fasta file, and assumes reference is present in the EAGER2 output directory (which I also assume is the execution directory) - but I'm not 100% sure.

**To Reproduce**
Pipeline info is attached.

**Operating System:**
 - OS: Ubuntu 14.04

**Additional context**
Please provide me with the following files:
[pipeline_report.txt](https://github.com/nf-core/eager/files/2571262/pipeline_report.txt)
[nextflow.log](https://github.com/nf-core/eager/files/2571266/nextflow.log)

**Comment by apeltzer** [comment]
Its still missing singularity apparently..   `env: singularity: No such file or directory`

**Comment by apeltzer** [comment]
Are you sure its installed and callable on that specific node?

**Comment by apeltzer** [comment]
Missing singularity is the issue here - once its added, either reopen or open a new issue :-)
