### ISSUE TITLE
Increase significance figures in general stats table

### ISSUE THREAD

**Issue by neija2611** [nf-core/eager#834]
When the mean coverage is below 0.05X, the general stats table only shows 0.0X
For low coverage data an increase in significance would be helpful.

When mean coverage is 0.02495, I'd like to see 0.025X.

**Comment by jfy133** [comment]
Hi @neija2611 

Hmm, that's a good question. I will definitely list this for the next release, but this might be a while as I'm working on re-writing the pipline into the nextflow version.

in the meantime however, you can maybe making a custom multiqc config by copying the base eager one here: https://github.com/nf-core/eager/blob/master/assets/multiqc_config.yaml

play around with the following parameters: https://multiqc.info/docs/#number-base-multiplier

and supply the file to your nextflow run command with `--multiqc_config <your_custom_config>.conf`

**Comment by jfy133** [comment]
Ok, I was wrong with my original suggestions, but I think I may have a solution via: https://multiqc.info/docs/#command-line-config

**Comment by jfy133** [comment]
Essentially we want to tweak this 

https://github.com/ewels/MultiQC/blob/75ef0ab9bbe33c24502be10c709ce374e736dbfe/multiqc/modules/qualimap/QM_BamQC.py#L549-L562

to include something like this 

https://github.com/ewels/MultiQC/blob/75ef0ab9bbe33c24502be10c709ce374e736dbfe/multiqc/modules/qualimap/QM_BamQC.py#L537

But I don't think it makes sense to have that directly in MQC as most modern people won't have the issue of low-coverage data

**Comment by jfy133** [comment]
@neija2611 this is going to be fixed by the MultiQC main dev [^1], so we will be able to add this once the next MultiQC release is out - but this wil ltake some time

[^1]: https://matrix.to/#/!pKqbkCfeANyNapVFFe:gitter.im/$LvBPDv9HbbpSD1Abdjn1j_ytUvDfL9LvewEC-5Y7lx8?via=gitter.im&via=matrix.org
