### ISSUE TITLE
Possibly faulty `samtools index` command?

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#84]
**Describe the bug**
When running with the `-singularity` profile on the branches/versions `-r shh-profile` and `-r 2.0.2`, the `bwa` module crashes on the `samtools index` on the sorted bamfile.

It appears there maybe a misplaced `-@` option which is not applicable to `samtools index`.

Samtools standard out/error is below:

```
[main] CMD: bwa samse -r @RG\tID:ILLUMINA-ABM006.A0101_S0_L002_R1_001\tSM:ABM006.A0101_S0_L002_R1_001\tPL:illumina hg19_MT.fasta ABM006.A0101_S0_L002_R1_001.combined.prefixed.fq.sai ABM006.A0101_S0_L002_R1_001.combined.prefixed.fq.gz
  [main] Real time: 7.227 sec; CPU: 6.184 sec
  index: invalid option -- '@'
  Usage: samtools index [-bc] [-m INT] <in.bam> [out.index]
  Options:
    -b       Generate BAI-format index for BAM files [default]
    -c       Generate CSI-format index for BAM files
    -m INT   Set minimum interval size for CSI indices to 2^INT [14]
```

**To Reproduce**
Run the following command (replace paired end data, index file as required):

```
nextflow run nf-core/eager \
--reads '/projects1/users/fellows/nextflow/eager2/my_test/data/ABM006.A0101/*_R{1,2}*fastq.gz' \
--pairedEnd \
--fasta '/projects1/users/fellows/nextflow/eager2/my_test/references/hg19_MT.fasta' \
--outdir '/projects1/users/fellows/nextflow/eager2/my_test/output_eager2' \
-profile singularity \
--max_cpus 4 \
--max_memory 16G \
-r 2.0.2
```

**Additional context**
Please provide me with the following files:
- `.nextflow.log` [nextflow.log](https://github.com/nf-core/eager/files/2581683/nextflow.log)
- `results/pipeline_info/...` [pipeline_report.txt](https://github.com/nf-core/eager/files/2581685/pipeline_report.txt)

**Comment by apeltzer** [comment]
I'm quite wondering why this wasn't caught by our CI tests at all. Samtools in the container should actually work fine and the `-@` option was present...

**Comment by apeltzer** [comment]
So my tests were correctly done - I guess indexing doesn't really benefit from parallelization anyways ;-)
