### ISSUE TITLE
A problem with Eager  at the DeDup level

### ISSUE THREAD

**Issue by More92** [nf-core/eager#846]
I’m running a sample with EAGER and I want to get no-merged data, following the instructions below:
-For the input file upload two Fastq (reads 1 e 2) and select the Single-End Data
-General settings:
FastQC analysis;
Adapter RM/Merging : CLIP&Merge (Perform only adapter clipping);
Mapping: CircularMapper;
Complexity Estimation;
Remove Duplicates with DeDup;
Damage calculation with mapDamage;
But the analysis dies when trying to remove the duplicates. The .log file reports: 
SamtoolsSortDeDup was executed with the following commandline: “samtools sort -[@ 10]() -m 3G /../OUTPUT/5-DeDup/file_name.fastq.fq.MT_realigned.mappedonly.sorted.qF.sorted.cleaned_rmdup.bam -o /../ OUTPUT/INPUT/5-DeDup/file_name.fastq.fq.MT_realigned.mappedonly.sorted.qF.sorted.cleaned_rmdup.sorted.bam “
“samtools sort: truncated file. Aborting”
Furthermore I can still find the following 10 multiple bam files in the 5-DeDup directory even if they should disappear once the final file(file_name.fastq.fq.MT_realigned.mappedonly.sorted.qF.sorted.cleaned_rmdup.sorted.bam. ) is created:
-fastq.fq.MT_realigned.mappedonly.sorted.qF.sorted.cleaned_rmdup.sorted.bam.tmp.0000.bam ( this is an example of one of the 10 files)
How can I manage this issue? 
Should I start again the analysis from the beginning or is there a way to skip the steps that went right?
I was also wandering if there is a way to know if the 10 files in the 5-DeDup directory are complete.
Lastly, I only manage to get the report file if I run more samples in a row, how can I get it analysing only one file?

**Comment by jfy133** [comment]
Output files indicate that this is eager1, so this is the wrong repository. I'll ask @apeltzer if there is a quick answer, but eager1 isn't supported anymore, so no promises... (Sprry)!)
