### ISSUE TITLE
Consider adding mitochondrial contamination estimator

### ISSUE THREAD

**Issue by roberta-davidson** [nf-core/eager#877]
## Is your feature request related to a problem? Please describe
I would like to be able to assess my samples for mitochondrial contamination as an indicator of contamination in general. This can be done with Schmutzi or ContamMix I believe.

## Describe the solution you'd like
Integrate Schumtzi mitochondrial contamination or similar into the pipeline as an additional option

## Describe alternatives you've considered
Currently am running it separately outside of eager, but it would be smoother if it could be achieved within eager, which already has other contamination estimators, but none based specifically on mitochondrial DNA.

**Comment by jfy133** [comment]
Hi @roberta-davidson 

this is something has been asked in the past, but unfortunately neither tool are on bioconda sadly ☹

Schmutzi could theoretically go into it, however, my experience with tools from that developer is that's better if they do that themselves. Maybe you can ask them to do so, then I'm happy to add it.

The source code for ContaMIX is not publically available so also not possible.
