### ISSUE TITLE
Allow pipeline to map to multiple references in one command

### ISSUE THREAD

**Issue by roberta-davidson** [nf-core/eager#878]
## Is your feature request related to a problem? Please describe
Currently have to run the eager pipeline twice if I want to map the same data to the human reference genome and then to the rCRS mitochondrial reference genome. 

## Describe the solution you'd like
The ability to specify Human ref genome and mito ref genome, and run both mappings in the same command. (Not competitive mapping, just simultaneously). 

## Describe alternatives you've considered
Currently, I'm just running eager twice, but no other parameters or input information change so this is redundant.

**Comment by roberta-davidson** [comment]
Actually I didn't really consider competitive mapping, although it may also work well but I haven't tried it myself. At this stage I'm simply performing two mappings and being stringent with variant calling to compensate for potential NUMTs.

**Comment by jfy133** [comment]
Well, the full human reference genome by default includes the chrMT/MT entry, so theoretically you are already mapping to both in a competitative mapping fashion already.

So I guess my question is why:

> At this stage I'm simply performing two mappings and being stringent with variant calling to compensate for potential NUMTs.

is not sufficient? What is the benefit of mapping separately (again, probably nothing wrong with the approach, I don't work with eukaryotes myself [anymore])

**Comment by roberta-davidson** [comment]
What we see when mapping to the whole reference genome is that for whatever reason, bwa preferentially maps reads to NUMTs instead of the MT, so there are always gaps at certain sites in the mitochondrial genome coverage, no matter the sequencing depth, so it's become common practice just to map separately to rCRS mito reference separately.

**Comment by jfy133** [comment]
Huh, ok good to know!

I will think about this indeed then when converting the pipeline to DSL2 then!

**Comment by roberta-davidson** [comment]
Great, thanks!! :)

**Comment by jfy133** [comment]
Dev note: I think we will have to have the option of CSV and/or a straight fasta. The CSV would have to have paths to optional indices

**Comment by maxibor** [comment]
The other problem with competitive mapping comes later when you want to do
some variant calling: because multi mapping read get a very low MAPQ score,
they are typically ignored by genotypers.
That's part of the reason why I've implemented
https://github.com/maxibor/adnamap

**Comment by jfy133** [comment]
that's also something I partly considered, the competitive mapping is used for very specific contexts (e.g. strain discrimination during pathogen screening), and like you said sort of breaks some assumptions with standard aligners. It an still be done if you manually combine your FASTAs and use e.g. bedtools with the FASTA headers of each genome as the 'feature' to extract read counts, which hsould be sufficient.

**Comment by jfy133** [comment]
Added for eager3 in https://github.com/nf-core/eager/pull/952
