### ISSUE TITLE
endorspy processes not cached properly on `-resume`

### ISSUE THREAD

**Issue by TCLamnidis** [nf-core/eager#880]
## Description of the bug

When a run fails/is killed, and then resumed, sometimes `endorspy` is not ran at all, leading to endogenous information missing from the multiqc report.

## Steps to reproduce

Start any run that includes endorspy, and kill the job before resuming the run. Even if endorspy has already run, it will not be picked up in the resumed run and will not appear in the multiqc report. 

## Expected behaviour

endorspy processes are cached normally and included in the output.

## Log files

Have you provided the following extra information/files:

- [ ] The command used to run the pipeline
- [ ] The `.nextflow.log` file 
- [ ] The exact error: 

## System

- Hardware: 
- Executor: 
- OS: 
- Version 

## Nextflow Installation

- Version: 21.04.0.5552

## Container engine

- Engine: singularity
- version: 3.7.1
- Image tag: nfcore/eager:2.4.2

## Additional context

The current output of the endorspy process is a tuple instead of a file channel. I have a feeling that might be causing the behaviour.

https://github.com/nf-core/eager/blob/43a239bd132b4a6ccf791d7052f537f3d22b700c/main.nf#L1812

The MQC output channel of another process for comparison:
https://github.com/nf-core/eager/blob/43a239bd132b4a6ccf791d7052f537f3d22b700c/main.nf#L691

In general, multiqc input channels are file channels, but there are cases where they are actually tuple channels. this should be fixed throughout.

**Comment by jfy133** [comment]
This was also reported by @KathrinNaegele  in the past

After insightful debugging assistance from @mahesh-panchal , I think we've identified the problem and have a possible solution.

Discussion: https://nextflow.slack.com/archives/C02T98A23U7/p1657268366386419

During lane/seqtype merge, we do a groupTuple, and for the `lane` `seqtype` metas, during this step these get converted into a nextflow object called 'ArrayBag'. It appears that for whatever reason (that we don't understand), something inside the ArrayBag objects changes between a cancelled/interupted run, causing the join to fail on these two elements.

The workaround is to replace the arraybag with a simpler object, e.g. string or integer.

**Comment by jfy133** [comment]
Done in https://github.com/nf-core/eager/pull/902
