### ISSUE TITLE
Operator `into` has been deprecated -- it's not available in DSL2 syntax

### ISSUE THREAD

**Issue by hypotheses** [nf-core/eager#884]
I have just install nextflow and pull eager to test with the command below and got the error as mentioned.

>./nextflow run nf-core/eager -profile test,docker
N E X T F L O W  ~  version 22.04.0
Pulling nf-core/eager ...
 downloaded from https://github.com/nf-core/eager.git
Launching `https://github.com/nf-core/eager` [golden_austin] DSL2 - revision: 43a239bd13 [master]

------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/eager v2.4.4
------------------------------------------------------

Operator `into` has been deprecated -- it's not available in DSL2 syntax

 -- Check script '.nextflow/assets/nf-core/eager/main.nf' at line: 198 or see '.nextflow.log' file for more details

**Comment by jfy133** [comment]
Hi @hypotheses please try adding `-dsl1` to the end of your command.

There is a new version of the nextflow language called dsl2 that has been made default in the latest version of nextflow (v22:04, I believe).

The -dsl1 flag tells nextflow to use the earlier version of the language, that eager is currently written in.

**Comment by hypotheses** [comment]
Thank you for your help. Adding `-dsl1` worked! 👯‍♂️
