### ISSUE TITLE
`get_software_versions` failing because of missing version files.

### ISSUE THREAD

**Issue by maxibor** [nf-core/eager#885]
(At least) on our EVA SGE cluster, the `get_software_versions` process is sometimes failing because of a lack of memory for the Java Virtual machine used by some programs (bug also reported by @alexhbnr and @arthurkocher ).

The `.command.log` contains this error:
```bash
Error occurred during initialization of VM
Unable to allocate 65536KB bitmaps for parallel garbage collection for the requested 2097152KB heap.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Two solutions to that:
- The quick fix: Increase the memory for the `get_software_versions` process
- The real fix: specify the Java virtual machine memory in the `get_software_versions` for the tools that use a JVM (with `-J-Xmx${task.memory.toGiga()}g `)
<!--

**Comment by maxibor** [comment]
More specifically, the `v_toolname.txt` of tools using JVM are all failing with one of the two errors:
- `Error occurred during initialization of VM`
- `Unable to allocate 65536KB bitmaps for parallel garbage collection for the requested 2097152KB heap.`

**Comment by jfy133** [comment]
@maxibor as we already have the fix for the missing threads for FastQC, I've changed my mind - you can make a PR if you want to add the `-Xmx` stuff to get software versions.
