### ISSUE TITLE
Typo in output documentation and output documentation reporting in pipeline summary

### ISSUE THREAD

**Issue by RodrigoBarquera** [nf-core/eager#895]
nf-core/Eager Team:

I found a typo in the documentation for Eager. In https://nf-co.re/eager/2.4.4/output#output-files section mapping/, it says:

"You will also find a corresponding BAM index file (ending in .csi or .bam)"

and it should say:

"You will also find a corresponding BAM index file (ending in .bai)"

Also, I have a suggestion for the documentation at the end of the MultiQC report/pipeline summary: you could add the paths to the main output files (.fq, .bam) there for a quick reference, especially for new users/changes in regular sequencing outputs.

Thanks.

**Comment by jfy133** [comment]
I won't add the paths to the main output files, as we have no idea what the user will cosnider the main output files (we have main possible).

However I have added a link to the output docs in the pipeline summary where this is all describe already
