### ISSUE TITLE
Circular generator crashes on bwa index when input fasta file does not end in .fasta

### ISSUE THREAD

**Issue by scarlhoff** [nf-core/eager#899]
Circular generator fails on bwa index when using hs37d5_MT_only.fa as reference input 

Relevant lines of code: 
https://github.com/nf-core/eager/blob/43a239bd132b4a6ccf791d7052f537f3d22b700c/main.nf#L1349-L1361

nf-core/eager v.2.4.4
nextflow v.22.04.0.5697

command:
nextflow run nf-core/eager -profile eva,archgen,MT_hs37 -c ~/eager2.config --input HPD_MT.tsv -r 2.4.4 -dsl1 -with-tower -name HPD_MT 

error:
Picked up _JAVA_OPTIONS: -XX:ParallelGCThreads=1
[bwa_idx_build] fail to open file 'hs37d5_MT_only_500.fasta' : No such file or directory

**Comment by apeltzer** [comment]
Yeah this would need a bugfix for DSL1. Other option is to wait for DSL2 version of EAGER _or_ renaming your fasta to have `.fasta` extension for the time being.
