### ISSUE TITLE
Review MultiQC Custom Content in Main Table

### ISSUE THREAD

**Issue by apeltzer** [nf-core/eager#90]
I'd like to have a better and improved report in the end, summarizing certain important metrics in a smart way, e.g. but not limited to. Naming is something I'd not like to standardize too much since different labs tend to have different names for certain metrics. 

- "Cluster Factor": (Number of duplicate reads / Total number of reads in sample)
    - Ideally, this would be summarized based on information retrieved from some modules running in the pipeline.
- "Target Efficiency": (Captured bases / targetted bases) 

... 

Could you please add things that are of specific interest to you? 
These here are on my ToDo list:

- mt/Nuc ratio 
- mapped reads / % mapped reads
- merged reads / % merged reads
- GC content 

Schmutzi / estimates for contamination 
....

Any ideas what you'd like to see here @EisenRa @jfy133 @JudithNeukamm ?

**Comment by EisenRa** [comment]
@apeltzer looking awesome so far!

Things that I think would be great are:

- DamageProfiler: both C->T/G->A, and fragment length distribution.
- In the 'General Statistics' section, % of genome with coverage >= 2, 3, 4. (Currently there is 1, 5, 10, etc.)
- Qualimap mapping scores

**Comment by jfy133** [comment]
Not so much a metric, but have 'number of reads after quality filtering' column.

**Comment by apeltzer** [comment]
To summarize a bit what Phil said, I guess we'll need a custom plugin for MultiQC to provide some of these here. 

So we should create a list of required metrics and how to compute them and have these available then.

**Comment by jfy133** [comment]
For reference, this are some of the typical EAGER 1 headers. I will update definitions (as I understand them) over the next couple of days.

- Sample Name
- # of Raw Reads prior Clip & Merge (C&M)
- # reads after C&M prior mapping
- # of Merged Reads
- % Merged Reads
- # reads not attempted to map
- # mapped reads prior RMDup
- # of Duplicates removed
- Mapped Reads after RMDup
- Endogenous DNA (%)
- Cluster Factor
- Mean Coverage
- std. dev. Coverage
- Coverage >= 1X in %
- Coverage >= 2X in %
- Coverage >= 3X in %
- Coverage >= 4X in %
- Coverage >= 5X in %
- # of reads on mitochondrium
- AVG Coverage on mitochondrium
- MT/NUC Ratio
- DMG 1st Base 3'
- DMG 2nd Base 3'
- DMG 1st Base 5'
- DMG 2nd Base 5'
- average fragment length
- median fragment length
- GC content in %

**Comment by jfy133** [comment]
Additional stuff from EAGER1 modules which wasn't in original ReportTable
- Genotyping stuff maybe from GATK? I don't know would be useful there or if there is a fast stats scanner (e.g. maybe from bcftools?)

Additional stuff which has been added to EAGER2 already
FastP 
- **# reads after PolyG trimming** Number of reads that were trimmed of poly-G tails. From fastp html report. [Might need to consider whether to also calculate this after C&M which has a length filter...)

**Comment by jfy133** [comment]
I can potentially supply an R/tidyverse script that converts a MultiQC Json to a nice table however a couple of things to note:  
  * I will still need a way to get a list of the IDs of things when I need to collapse stats across multi lane samples
  * Apparently MultiQC Json isn't meeting JSON standards due to some of the values of the module stats files being varied (i.e. NA vs NaN vs null etc), so I have to do some hacky things to clean that up. Might be worth speaking to MultiQC crew to standardise that somehow (which would require per-module reporting of what each 'missing data' value standards for)
  * Not sure how I will deal with DeDup stats of multi-lane things.

**Comment by jfy133** [comment]
Extra values for the polyG to consider is effect on GC content, but we need to decide how to display this (i.e. which modules to get this info from).

**Comment by apeltzer** [comment]
Need to update this according to requirements we have - there have been a lot of updates on this one recently, e.g. supprt for mtnucratio in MultiQC, mean coverage updates in MultiQC using QualiMap.

**Comment by jfy133** [comment]
Most needed stuff is there, but no endogenous DNA. Maybe a small python script required? @aidaanva

**Comment by aidaanva** [comment]
I can do it

**Comment by apeltzer** [comment]
Your script could actually run in the `process multiqc` step and simply divide the output as requested, then creating some custom content for multiqc itself :-) https://github.com/ewels/MultiQC/blob/master/docs/custom_content.md

**Comment by jfy133** [comment]
Endogenous DNA added. Will close for for 2.1, but can reopen in the future for next MultiQC Release
