### ISSUE TITLE
Mapped reads as input to metagenomic screening

### ISSUE THREAD

**Issue by ilight1542** [nf-core/eager#904]
# nf-core/eager feature request

Allow mapped reads to be converted to fastq for input into metagenomic screening steps.

## Is your feature request related to a problem? Please describe

Lack of flexibility in choosing what reads go to metagenomic screening steps

## Describe the solution you'd like

Ability to select either mapped reads (with a given mapping quality threshold) OR unmapped reads as conversion to fastq for input into metagenomic screening step. (eg run mapping against a fasta of all microbial diversity, discard all non-mapped reads, run all mapped reads into metagenomic screening)

## Describe alternatives you've considered

No current work arounds for getting mapped reads --> fastq for processing. Alternative is to have reference genome include more species that you want to filter out.

## Additional context

A DAG diagram of where reads are ending up as inputs to other tools would be a huge help for interpretability of the pipeline, and as a potential ""dry"" run of the pipeline to make sure users know what will happen to their data.

**Comment by jfy133** [comment]
> A DAG diagram of where reads are ending up as inputs to other tools would be a huge help for interpretability of the pipeline, and as a potential ""dry"" run of the pipeline to make sure users know what will happen to their data.

Not sure what you mean here? Dry run stuff would be at a nextflow level however and not in scope here.

**Comment by jfy133** [comment]
Done in  https://github.com/nf-core/eager/pull/941
