### ISSUE TITLE
DSL2: metagenomics

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#923]
- BBDUK
- HOSTREMOVAL
- MALT/KRAKEN
- MALTEXTRACT
- KRAKENPARSE

## New 

- Option: mapped OR unmapped reads to metagenomic screeming
- KRAKENUNIQ
- METAPHLAN3
- PRINSEQ (alternative complexity filterer)

**Comment by merszym** [comment]
![metagenomics](https://user-images.githubusercontent.com/45922464/225889185-214270ed-8931-4962-884d-79a1f3b22e8b.png)

Hey, I outlined the metagenomics-pipeline. If you have any comments/ things to add, please let me know!

**Comment by jfy133** [comment]
A few comments:

-`fastq_for_metagenomics?` yes can be both merged and paired
- contaminants maybe not necessary for bbduk, I just use the entropy filter in that... but might be interesting
- Missing `kraken-parse` results dir, but otehrwise sounds good to me! We could also replace the `kraken-parse` local module with `krakentools`: https://nf-co.re/modules/krakentools_combinekreports

**Comment by merszym** [comment]
Current progress:

![wip](https://user-images.githubusercontent.com/45922464/227974833-583b96a2-2ee1-4f32-8d18-477ecd70eb8d.png)

**Comment by merszym** [comment]
@ilight1542 The current version in dsl2-metagenomics works for the following tests 

[tests.md](https://github.com/nf-core/eager/files/11847236/tests.md)
