### ISSUE TITLE
New module: calmd

### ISSUE THREAD

**Issue by JackCurragh** [nf-core/eager#925]
#778 lists samtools calmd as needing DSL2 module creation.

**Comment by jfy133** [comment]
We realised actually this has (and has already been) to be with pmd directly, so we don't need a separate module for this. But @JackCurragh will finish it up anyway as other people might find it useful

**Comment by JackCurragh** [comment]
@jfy133 - Again, learning as I go but did not find [this](https://github.com/nf-core/modules/issues/839#issue-1025647807) more appropriately placed issue from Hackathon 2021 when I first looked. Possibly because I was looking within Eager. 

Should I close this issue and proceed by adding that issue to the project board assigning it issue to myself?

**Comment by jfy133** [comment]
No worries! You can assign yourself to both and close both when the module is merged.

Feel free to ping me for module review when you're PR is opened into modules.

**Comment by jfy133** [comment]
kModule added: https://github.com/nf-core/modules/issues/839#issue-1025647807
