### ISSUE TITLE
Change read groups for genotyping when using MultiVCFAnalyzer

### ISSUE THREAD

**Issue by aidaanva** [nf-core/eager#928]
## Is your feature request related to a problem? Please describe

This is problem a when running multiVCFAnalyzer and more than one library have been merged. When the merging happens, each of the libraries has their own read group, which results in multiple columns in the vcf output, that is then not read properly by MultiVCFAnalyzer, which results in the genotyping of only one of the libraries present in the bam file. 

## Describe the solution you'd like

When one runs MultiVCFAnalyser, the readgroup should be changed before the genotyping occurs to the same readgroup for all of the libraries within the bam file

**Comment by jfy133** [comment]
done in https://github.com/nf-core/eager/pull/930
