### ISSUE TITLE
mapdamage2 --seq-length parameter

### ISSUE THREAD

**Issue by ashildv** [nf-core/eager#933]
## Is your feature request related to a problem? Please describe

I wanted to run mapdamage rescale with 15 bp at the end of each read since I have some samples with a lot of damage. However, that seems only to be possible if the  mapdamage --seq-length parameter is also increased from the default of 12 bp set in eager. However, it is not currently possible to adjust the --seq-length parameter in nf-core/eager. Could this be added in the next release? Now I have to run it outside the pipeline, which is annoying

## Describe the solution you'd like

Implement the --seq-length paramter from mapdamage.

**Comment by apeltzer** [comment]
Fixed in #935
