### ISSUE TITLE
Missing "=" in mapdamage rescale command

### ISSUE THREAD

**Issue by ashildv** [nf-core/eager#934]
## Check Documentation

I have checked the following places for your error:

- [ ] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [ ] [nf-core/eager pipeline documentation](https://nf-co.re/nf-core/eager/usage)
      - nf-core/eager FAQ/troubleshooting can be found [here](https://nf-co.re/eager/usage#troubleshooting-and-faqs)

## Description of the bug

This is the command nf-core eager ran, there is missing equal sign here: " --rescale-length-5p 15"

From the .command.sh file:
#!/bin/bash -euo pipefail
mapDamage -i sample_rmdup.bam -r reference.fasta --rescale --rescale-out sample_rmdup_rescaled.bam --rescale-length-5p 15 --rescale-length-3p=15
samtools index sample_rmdup_rescaled.bam

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: `nextflow run ...`
2. See error: _Please provide your error message_

## Log files

Have you provided the following extra information/files:

- [ ] The command used to run the pipeline
- [ ] The `.nextflow.log` file 
- [ ] The exact error: 

## System

- Hardware: 
- Executor: 
- OS: 
- Version 

## Nextflow Installation

- Version: 

## Container engine

- Engine: 
- version: 
- Image tag:

**Comment by apeltzer** [comment]
Fixed in #935
