### ISSUE TITLE
Found unexpected parameters --qualitybase: 64

### ISSUE THREAD

**Issue by KeLi1018** [nf-core/eager#938]
Hi EAGER team! I'm running eager v.2.4.6 on a single end sample but I've had some issues.

Here is the code:
`nextflow run nf-core/eager --single_end --input "*.fastq.gz" --qualitybase 64 --fasta "reference.fna" -profile singularity --outdir ./`

And the Nextflow error:

WARN: 
Found unexpected parameters:
 --qualitybase: 64

Command error: 
  Error reading FASTQ record at line 1; aborting: 
      Phred+33 encoded quality score is greater than the expected maximum of 41 (J). 
      Please verify the format of these files. 
      If the quality scores are actually Phred+64 encoded, then use the 
      '--qualitybase 64' command-line option.

Sorry, I couldn't work out how to fix this. Thanks, its a very helpful pipeline.

**Comment by jfy133** [comment]
Hi @KeLi1018 !

`--qualitybase` is a AdapterRemoval parameter (the error is from AdapterRemoval itself).

If I remember correctly, to change this via the pipeline you need to use `--qualitymax`: https://nf-co.re/eager/2.4.6/parameters#qualitymax
