### ISSUE TITLE
Error in picard markduplicates step

### ISSUE THREAD

**Issue by nilesh-tawari** [nf-core/eager#96]
Hi @apeltzer,

Thanks for the wonderful pipeline. I am trying to use pipeline for mordern DNA analysis. While running I encountered error in picard markduplicates step:

Below is the command used to run pipeline,

```
nextflow run nf-core/eager  --pairedEnd --reads '*_R{1,2}_001.fastq.gz' -c ~/.nextflow/config-eager --fasta genome.fa --saveReference --skip_damage_calculation --bwamem --dedupper markdup
```
Below is the snippet from error.

```

Command executed:

  picard MarkDuplicates INPUT=sample.sorted.bam.filtered.bam OUTPUT=sample.sorted.bam.filtered.markDup.bam REMOVE_DUPLICATES=TRUE AS=TRUE METRICS_FILE=sample.sorted.bam.filtered.markdup.metrics" VALIDATION_STRINGENCY=SILENT

Command exit status:
  2

Command output:
  (empty)

Command error:
  .command.sh: line 2: unexpected EOF while looking for matching `"'

```
There is formetting error in .commands.sh file

Thank you

**Comment by apeltzer** [comment]
Hi @nilesh-tawari !
Please use the `-r dev` branch for now, I included a fix for your problem that should resolve the missing `"` in 018a522f9f4fb9199aaf2472b91959fee15f6c64 ! 

I'll close the issue, please re-open if the problem persists after this!

**Comment by nilesh-tawari** [comment]
@apeltzer, Thanks yes the issue is solved. One more minor bug, the `pigz` dependency is missing in conda environment file. Hence, pipeline fails.

**Comment by apeltzer** [comment]
Hm, its not in the `dev` branch, but the stable pipeline release uses something else. I'll probably fix the 1-2 remaining issues today and release a new minor release to fix all of these.
