### ISSUE TITLE
bwa time issue / threads 

### ISSUE THREAD

**Issue by Angelika-2Z-Borowiecka** [nf-core/eager#977]
Hello,

I am contacting you because, I have an issue with a large file that ends bwa after 4h, as you can see in the error below : 

```
Pipeline completed with errors-
Error executing process > 'bwa (sample)'

Caused by:
 Process exceeded running time limit (4h)
```

In addition I used the following parameters, and it does not seem to work either: 

```
Max job request options
  max_cpus                     : 35
  max_memory                   : 128 GB
  max_time                     : 440.h
```
 
Finally I would like to note that for this kind of steps it would be potentially useful to be able to modify the number of threads. (unless I'm mistaken, it doesn't seem possible yet for bwa). Is there a possibility to work around that ? 

Thank you for taking the time to read this message.

**Comment by jfy133** [comment]
Hi @Angelika-2Z-Borowiecka !

Both increasing time and number of CPUs are possible!

Please see the documentation here: 

https://nf-co.re/docs/usage/configuration#max-resources

The `max_` acts as a limit, not actually increasing resources (first section in link above). The section immediately after (Tubing...) tells you how to make a config file in increase resources such as RAM, CPUs and walltime.

If you still have problems feel free to re-open this issue :)
