### ISSUE TITLE
Mapping Quality Filtering

### ISSUE THREAD

**Issue by jfy133** [nf-core/eager#99]
**Is your feature request related to a problem? Please describe.**
One missing functionality that is in EAGER1 not currently in EAGER2 (as far as I can see from the help message/documentation) is map quallity filtering.

This is something that is commonly carried out in pathogen work out of MPI-SHH Jena.

**Describe the solution you'd like**
`samtools view` step during SAM to BAM conversion to additionally allow removal of reads under a specified mapping quality.

A flag possibility would be: `--mapping_quality_filter` or `--mapping_quality_value`

This should also produce some statistics so the difference between unfilterd/filtered results can be recorded in a MultiQC general table.

**Comment by apeltzer** [comment]
Ah it is there... but probably again hidden in plain sight :-( 

https://github.com/nf-core/eager/blob/dev/docs/usage.md#--bam_mapping_quality_threshold

**Comment by jfy133** [comment]
Whoops my bad!
