### ISSUE TITLE
Hello! I'm not shure this is the right place to ask for help but I'm having problems when running MaltExtract, I get this error:  Error in image.default(x = 1:ncol(red.res), y = 1:nrow(red.res), z = t(red.res),  :      increasing 'x' and 'y' values expected   Calls: image -> image.default

### ISSUE THREAD

**Issue by crisamor** [nf-core/eager#991]
## Check Documentation

I have checked the following places for your error:

- [x] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [x] [nf-core/eager pipeline documentation](https://nf-co.re/nf-core/eager/usage)
      - nf-core/eager FAQ/troubleshooting can be found [here](https://nf-co.re/eager/usage#troubleshooting-and-faqs)

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: `nextflow run ...`
2. See error: _Please provide your error message_

## Log files

Have you provided the following extra information/files:

- [x] The command used to run the pipeline
- [x] The `.nextflow.log` file 
- [x] The exact error: 

## System

- Hardware: 
- Executor: 
- OS: 
- Version 

## Nextflow Installation

- Version: 

## Container engine

- Engine: 
- version: 
- Image tag:

**Comment by jfy133** [comment]
Hi @crisamor !

The error is already known, you can see the issue on the AMPs repository [here](https://github.com/keyfm/amps/issues/4).

Maybe you can report you have the same issue there :) as this isn't a problem with nf-core/eager itself
